### ISSUE TITLE
Hovering over a function-valued variable should give a link to the function definition

### ISSUE THREAD

**Issue by bzbarsky** [devtools-html/debugger.html#626] opened 2016-08-30 16:04 UTC
Consider this testcase:

``` html
    <script>
      function myFunction() {
      }
      window.addEventListener("foo", myFunction);
    </script>
```

Load it in Firefox, breakpoint on line 4 (the addEventListener call), reload.  While stopped at the breakpoint hover over the second argument to addEventListener.

I see a popup that shows various information about the function (properties, scope, etc).  What it doesn't have is a nice clickable link to the function definition.  Chrome's developer tools do have such a link in this situation.

The necessary info (file/line) should be extractable from the function object via its JSScript....

**Comment by bgrins** [comment] 2016-08-30 16:11
Screenshot of popup in chrome with source link:

<img width="525" alt="variable popup" src="https://cloud.githubusercontent.com/assets/95570/18097151/9dbd7b6e-6e91-11e6-9515-2aa261a17772.png">

**Comment by bgrins** [comment] 2016-08-30 16:14
The variable popup in the XUL UI wraps the variables view widget.  Guessing the variable popup in this UI will wrap the Object Inspector.

Would need to decide if this source link should be part of the header of a popup, or if it should be part of the Object Inspector.  IOW, should the link be included when the variable is shown in other places where the Object Inspector will be used, like the console output.

**Comment by jlongster** [comment] 2016-08-31 13:27
This isn't in the scope of what I call the "object inspector" though. I think this will be special functionality in the debugger, with it listening to events in the editor. The console doesn't use the editor, etc, so it will have to hook it up differently if it wants it. We could share the functionality that extracts all this info though. This will be in the next phase; right now we're focusing on landing the current debugger.

**Comment by clarkbw** [comment] 2016-08-31 14:52
Test case: http://s.codepen.io/clarkbw/debug/PGYXoN (breakpoint line 24 of PGYXoN)

**Comment by jasonLaster** [comment] 2016-11-23 20:03
Here's the old code

https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/views/variable-bubble-view.js

**Comment by nickolay** [comment] 2016-12-06 00:04
I am confused as to whether debugger.html has _any_ kind of tooltip when hovering any kind of variable variable.  The initial description here implies that it does (and requests an enhancement for the function-valued variables), while #1293 (marked as a duplicate of this issue) implies that it doesn't... Can anyone clarify?

**Comment by jasonLaster** [comment] 2016-12-06 00:08
Sorry it's not clear. 

We're missing the tooltip, but that'd be a great next step.

**Comment by bzbarsky** [comment] 2016-12-06 02:35
> I am confused as to whether debugger.html has any kind of tooltip

My initial bug report was about the Firefox devtools as they existed at the point when I filed the bug.  I was told to file it in this repo.  Those devtools did have a tooltip, but it was missing some information I wanted.  The change to debugger.html then removed even the info that we _used_ to have.  :(

**Comment by bzbarsky** [comment] 2016-12-06 02:35
And I think marking https://github.com/devtools-html/debugger.html/issues/1293 as a duplicate of this one wasn't correct; if this issue is resolved as written we'll have the link to the function definition, but not the info https://github.com/devtools-html/debugger.html/issues/1293 is asking for!

**Comment by jasonLaster** [comment] 2016-12-06 02:52
Sorry for the regression :/. 

The debugger was a total rewrite. I'll clean up the issue description soon as we have a much better product doc in the works. 

In reality, were not great about talking about upcoming work. We should get a lot better on that front!

We're planning on having a link to the definition and a formatted variable. 

We also want some goodies like add to watch expression. What extra info are you looking for?

**Comment by bzbarsky** [comment] 2016-12-06 07:16
The extra info that used to be there was some information about scope chain, as I said.  It doesn't have to be in the popup, if it's accessible some other way.

**Comment by jasonLaster** [comment] 2016-12-22 17:32
👍  Thanks @jnachtigall for finding this! I'll be sure to investigate soon, unless you want to hack on a prototype

CC @juliandescottes is the hover popup/tooltip guy

**Comment by jnachtigall** [comment] 2016-12-22 20:38
>  I'll be sure to investigate soon, unless you want to hack on a prototype.

@jasonLaster Appreciated, but sorry, no time, unfortunately (kids, job, life - in random order ;-) Filing a bug report is much easier (and something I can do "in between") than actually fixing it. Kudos to you and your team, thus.

**Comment by jasonLaster** [comment] 2016-12-22 22:54
Understood :) thanks for the input so far!

You're one of our main part time PMs :P

And happy holidays

**Comment by jasonLaster** [comment] 2016-12-30 17:03
closing this as the work will be tracked in #1574

**Closed by jasonLaster** 2016-12-30 17:03 UTC
Labels: difficulty: hard, enhancement

**Comment by bzbarsky** [comment] 2016-12-30 19:07
@jasonLaster How will the work be tracked there if the information about what work needs to happen isn't present there?  ;)

**Comment by jasonLaster** [comment] 2016-12-30 19:08
It will look like other tracking issues soon :)

**Comment by bzbarsky** [comment] 2016-12-30 20:00
<shrug>.  I'm giving up on spending time on this, but I don't see how you will keep track of the specific feature requested here without having an issue about that feature, and in that case why that shouldn't be this issue.  The most likely outcome is that it will just get forgotten.
