### ISSUE TITLE
Idea: Use Icons within Tabs Dropdown

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#4571] opened 2017-11-03 02:03 UTC
<img width="730" alt="context" src="https://user-images.githubusercontent.com/46655/32358109-1f765532-c011-11e7-95aa-65b6dd0bdcc5.png">

In the overflow tabs menu, I think it would be sweet to show the pretty print icon for pretty printed tabs.

**Comment by jasonLaster** [comment] 2017-11-03 02:08
hmm... i kinda want to kill this dropdown and put the open tabs in the new quick open modal:

cmd+p would open the modal w/ the open tabs on the top of the list

@wldcordeiro thoughts

**Comment by darkwing** [comment] 2017-11-03 02:09
Relying on Command+P is difficult as there's no visual cue, if I'm understanding you correctly.

**Comment by jasonLaster** [comment] 2017-11-03 02:10
yep... agreed. I guess every editor does it differently, and i feel i don't miss it when its not there. e.g. sublime

**Comment by jasonLaster** [comment] 2017-11-17 14:13
Closing this issue and moving to the [enhancements](github.com/devtools-html/debugger.html/projects/5) board. 

* We will hopefully be able to prioritize it in the near future. 
* The issue is closed temporarily, but feel free to continue discussing the issue

#enhancements

**Closed** 2017-11-18 20:43 UTC
Labels: enhancement, not-available
