### ISSUE TITLE
[Source Tree] Need left padding

### ISSUE THREAD

**Issue by bomsy** [devtools-html/debugger.html#4253] opened 2017-10-03 12:00 UTC
![image](https://user-images.githubusercontent.com/792924/31124046-985fc88c-a83a-11e7-8021-e5920e6f9a16.png)

**Comment by mateusortiz** [comment] 2017-10-03 18:47
I can work on this. 😄

**Comment by jasonLaster** [comment] 2017-10-03 18:48
@mateusortiz it's yours

**Comment by mateusortiz** [comment] 2017-10-03 18:53
👍  thanks @jasonLaster

**Comment by darkwing** [comment] 2017-10-03 22:15
This is a duplicate of https://github.com/devtools-html/debugger.html/issues/4190 but we have two contributors working on them so keeping this open

**Comment by bomsy** [comment] 2017-10-05 14:44
Hey @mateusortiz Found where the issue was

Here's a good diff to help
```diff
diff --git a/src/components/PrimaryPanes/SourcesTree.js b/src/components/PrimaryPanes/SourcesTree.js
index 151a774..6ff6465 100644
--- a/src/components/PrimaryPanes/SourcesTree.js
+++ b/src/components/PrimaryPanes/SourcesTree.js
@@ -233,7 +233,7 @@ class SourcesTree extends Component {
     return (
       <div
         className={classnames("node", { focused })}
-        style={{ [paddingDir]: `${depth * 15}px` }}
+        style={{ [paddingDir]: `${depth * 15 + 5}px` }}
         key={item.path}
         onClick={() => {
           this.selectItem(item);
```

**Closed** 2017-10-06 07:49 UTC
Labels: bug, in progress
