### ISSUE TITLE
[Breakpoints] lost in formatted / prettified source tabs after reloading

### ISSUE THREAD

**Issue by jryans** [devtools-html/debugger.html#1686] opened 2017-01-11 21:01 UTC
STR:

1. Format some minified source file
2. Add a breakpoint
3. Reload the page being debugged

ER:

The breakpoint should be persisted and be possible to hit on reload.

AR:

The formatted source is lost and the breakpoint goes away.

**Comment by jasonLaster** [comment] 2017-01-11 22:39
@jryans mind giving a URL where we see this?

I mention that because [this](http://recordit.co/RAKyZIXvhI) works with [todomvc](https://devtools-html.github.io/debugger-examples/examples/todomvc/)

**Comment by jryans** [comment] 2017-01-11 22:49
@jasonLaster Well... I can't seem to reproduce now... Maybe I was just choosing a bad line...?

Sorry! Will reopen if there's more to say.

**Comment by miketaylr** [comment] 2017-10-12 18:07
This isn't working for me, what feels like 90% of the time:

http://recordit.co/fGux1xdx4R

When it does work, clicking on methods in the Call Stack panel takes me to the minified source again, which... isn't fun. Unfortunately I can't seem to get a screencast of that, because it's just failing.

**Comment by miketaylr** [comment] 2017-10-12 18:13
Here's a screencast of clicking through the call stack when the breakpoint does stick (on a simpler page: https://miketaylr.com/code/input-type-attr.html) not doing anything useful:

http://recordit.co/q7CrccRfcH

**Comment by miketaylr** [comment] 2017-10-12 18:14
> @jryans mind giving a URL where we see this?

@jasonLaster If you want to reproduce from the first screencast, STR are at https://github.com/webcompat/web-bugs/issues/12325#issuecomment-336168501. the second is in my previous comment -- happy to file a new bug for that if you prefer.

**Comment by jasonLaster** [comment] 2017-10-12 20:03
Thanks @miketaylr can you add an STR here too

**Comment by jasonLaster** [comment] 2017-12-15 16:23
This is a dupe of #3532

**Closed** 2018-02-27 21:04 UTC
