### ISSUE TITLE
Massive hang during page load with Debugger open

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#3988] opened 2017-09-12 18:34 UTC
STR

- Opened Debugger on a test page
- Navigated to Slack
- Cmd-R reloaded the page (Scratchpad told me that Cmd-R executes the line)

AR: Massive hanging

Initial analysis, to be refined:

Debugger in background: https://perfht.ml/2wnmVcS

- Choking on data and creating react elements

Another profile with Debugger in foreground: https://perfht.ml/2wn6RYD

- Something with Netmonitor

**Comment by ochameau** [comment] 2017-09-15 08:18
This is a duplicate of issue 3736, where you can find similar stacks in the profiler.

**Comment by jasonLaster** [comment] 2017-09-25 14:02
I looked into the perf profile this weekend and found two issues, codemirror and the source tree. Here are three profiles:

1. [no debugger](https://perfht.ml/2xAckz9)
2. [debugger open w/o the editor](https://perfht.ml/2xA3VLT)
3. [debugger open](https://perfht.ml/2xAtRqG)



### CodeMirror is the big offender

The first 30 seconds is spent responding to two significant events: `newSource` and `loadSourceText`. 

* `newSource` is the long spikey period from 6s to 19s
* `loadSorceText` is the steady period from 19s to 23s.

![Screen Shot 2017-09-25 at 9.56.00 AM.png](https://shipusercontent.com/d2e204615f72844001905ea3a57a003e/Screen%20Shot%202017-09-25%20at%209.56.00%20AM.png)

If we were to disable the editor, then we'll see that the `newSource` events are handled much faster. It now takes 3s instead of 13s.

<img src='https://shipusercontent.com/2a240298642b3a690b7f08409891c591/Screen%20Shot%202017-09-25%20at%209.59.33%20AM.png' title='Screen Shot 2017-09-25 at 9.59.33 AM.png' width=722>

We can definitely speed up the tree if we do a couple small optimizations so we memoize parsed URLs and improve the Immutable Source Record perf. We can also ofcourse improve the tree data structure as well. 




### The source tree is slow



### Here's how i disabled the editor

```diff
diff --git a/src/components/Editor/index.js b/src/components/Editor/index.js
index 47714d3..5bd7e0e 100644
--- a/src/components/Editor/index.js
+++ b/src/components/Editor/index.js
@@ -105,9 +105,9 @@ class Editor extends PureComponent {
       return;
     }

-    this.setSize(nextProps);
-    this.setText(nextProps);
-    resizeBreakpointGutter(this.state.editor.codeMirror);
+    // this.setSize(nextProps);
+    // this.setText(nextProps);
+    // resizeBreakpointGutter(this.state.editor.codeMirror);
   }

   setupEditor() {
@@ -125,7 +125,7 @@ class Editor extends PureComponent {
     const { codeMirror } = editor;
     const codeMirrorWrapper = codeMirror.getWrapperElement();

-    resizeBreakpointGutter(codeMirror);
+    // resizeBreakpointGutter(codeMirror);
     debugGlobal("cm", codeMirror);

     codeMirror.on("gutterClick", this.onGutterClick);
@@ -152,7 +152,7 @@ class Editor extends PureComponent {
       codeMirror.on("gutterContextMenu", (cm, line, eventName, event) =>
         this.onGutterContextMenu(event)
       );
-
+
       codeMirror.on("contextmenu", (cm, event) => this.openMenu(event, cm));
     } else {
       codeMirrorWrapper.addEventListener("contextmenu", event =>
@@ -511,6 +511,7 @@ class Editor extends PureComponent {
   }

   setText(nextProps) {
+    return;
     if (!this.state.editor) {
       return;
     }
@@ -537,6 +538,8 @@ class Editor extends PureComponent {
   }

   showMessage(msg) {
+    return;
+
     if (!this.state.editor) {
       return;
     }
diff --git a/src/utils/editor/source-documents.js b/src/utils/editor/source-documents.js
index c930379..5a51c0c 100644
--- a/src/utils/editor/source-documents.js
+++ b/src/utils/editor/source-documents.js
@@ -26,12 +26,14 @@ function clearDocuments() {
 }

 function resetLineNumberFormat(editor: Object) {
+  return;
   const cm = editor.codeMirror;
   cm.setOption("lineNumberFormatter", number => number);
   resizeBreakpointGutter(cm);
 }

 function updateLineNumberFormat(editor: Object, sourceId: string) {
+  return;
   if (!isWasm(sourceId)) {
     return resetLineNumberFormat(editor);
   }
```

**Comment by jasonLaster** [comment] 2017-09-25 15:43
Here is @ochameau's patch: 

> In the call tree, see the first line? i.e. exports.makeInfaillible expand this 4 or 5 times, you will see newSource from debugger.js

From this you could see that `SourcesTree.componentWillReceiveProps` is slow.
Mostly because of immutable.js. It see a 3x win if I replace it with a naive manual check.

See this patch (sorry, it is against the webpack bundle):
https://bugzilla.mozilla.org/page.cgi?id=splinter.html&bug=1399242&attachment=8909337

Also, we call a url module helper too many times. We shoud avoid calling it especially in the hot codepaths. Note that we should be using web "URL" constructor instead of this.
https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

**Comment by digitarald** [comment] 2017-09-25 16:12
Just a FYI for debugging perf, if you wrap the code that calls into codemirror with `performance.mark` and `performance.measure` it would show them in the marker view.

**Comment by ochameau** [comment] 2017-09-25 22:47
\o/ I'm so glad to see you use the profiler! Hopefully you will start a new trend in the team :-)

> CodeMirror is the big offender

I completely missed the impact of codemirror in the profile, good catch.
It looks like showMessage method is called a lot of times `showMessage(Loading…)` when you reload and have a source already selected. I think there is also unexpected number of `newSource` events coming from the actors. But the client should not be so slow by updating this "loading..." message, which is always identical. It looks like you can see all these calls to `showMessage(Loading…)` by filtering with "codemirror" in the profiler, you will see a bunch of spikes when reloading slack.

**Comment by codehag** [comment] 2017-10-04 12:05
@jasonLaster what is the status on this?

**Comment by jasonLaster** [comment] 2017-10-04 13:57
@codehag lets see what our perf is like after the source tree work lands.

**Comment by ochameau** [comment] 2017-10-04 14:00
Are you able to push to try a given debugger PR? (to have talos/DAMP test)
(if yes, the try syntax to execute DAMP is this one `try: -b o -p linux64 -u none -t g2-e10s --rebuild-talos 6`)

**Comment by jasonLaster** [comment] 2017-11-07 15:39
Slack is now reasonably fast.

**Closed** 2017-11-07 15:38 UTC
Labels: performance
