### ISSUE TITLE
Debugger stops at unexpected places

### ISSUE THREAD

**Issue by salomvary** [devtools-html/debugger.html#7748] opened 2019-01-17 21:45 UTC
This issue happens when debugging code on a codebase that uses Tone.js, a Web Audio library.

Steps to reproduce:

- Open https://tonejs.github.io/examples/daw.html
- Set a breakpoint on the first line of `Tone.Transport.prototype.start` in Transport.js
- Click the play button in the example app
- Try to step into `Tone.isDefined`

Expected: the debugger steps into `Tone.isDefined`.

Actual: various unexpected things happen (non-deterministic), for example one or more of these:

- The debugger steps into `Tone.Emitter.prototype.emit` instead
- Even if I hit Resume, it stops in `Tone.Emitter.prototype.emit` again (forever)
- The debugger does not stop on any breakpoint but the audio playback completely freezes
- The debugger steps at some other weird place
- Disabling or removing all breakpoints allows resuming but once re-enabled, the debugger stops again (even if no code path with breakpoints runs)

Screen recording: https://www.youtube.com/watch?v=eqYuCGL184o&feature=youtu.be

Tested on Firefox 64.0.2 and a local `debugger.html` instance from latest master (8f5a26a34a4b7063be0834a59e2af619c9bb1638).

The problem might be related to [how Tone.js generates high frequency clock ticks using a worker](https://github.com/Tonejs/Tone.js/blob/0e3238e742bfe723de8bea014ae4b727c3b3b97c/Tone/core/Context.js#L422-L449).

**Comment by jasonLaster** [comment] 2019-01-17 21:51
CC @bhackett1024

**Comment by bhackett1024** [comment] 2019-01-17 22:00
Hi, I just tested this a couple times on a local build and was able to step into Tone.isDefined both times.  Are you able to reproduce this on a nightly build?  Last month there were several fixes that may have taken care of this problem but they are not in release builds of firefox yet.

**Comment by salomvary** [comment] 2019-01-17 22:13
@bhackett1024 Works in Nightly as expected! Now I wonder when this will get released:)

**Comment by darkwing** [comment] 2019-01-17 23:07
I'm going to close this since everyone believes Nightly looks good.  Thank you for reporting @salomvary !

**Closed by darkwing** 2019-01-17 23:07 UTC
Labels: not-available
