### ISSUE TITLE
Source maps generated by Browserify not working

### ISSUE THREAD

**Issue by belen-albeza** [devtools-html/debugger.html#1654] opened 2017-01-09 18:26 UTC
Source maps generated by Browserify + Exorcist don't seem to be working on Nightly.

Try the following example: [sourcemaps-bug.zip](https://github.com/devtools-html/debugger.html/files/694321/sourcemaps-bug.zip)

Note that source maps appear under the "no domain", separated from the generated bundle:

![screen shot 2017-01-09 at 19 19 16](https://cloud.githubusercontent.com/assets/63681/21777888/44ae64a2-d6a1-11e6-8975-71bb9830bb72.png)

When clicking in the console to see the source for the error, I'm taken to the source of `bundle.js` instead of the relevant source file (`main.js`).

Note: these source maps do work in Chrome, so I'm don't think it's a browserify/exorcist bug, but maybe something related to the paths

**Comment by jasonLaster** [comment] 2017-01-09 18:41
thanks @belen-albeza

**Comment by clarkbw** [comment] 2017-01-10 02:26
I wonder if this is related to #1439

**Comment by jasonLaster** [comment] 2017-02-04 17:13
The next step is to add this example to our [examples] repo and reproduce it.

[examples]: https://devtools-html.github.io/debugger-examples/

**Comment by clarkbw** [comment] 2017-03-12 19:04
Should make sure that @jryans has seen this as well.  I'm sure its part of a number of other issues already filed in bugzilla.

**Comment by jryans** [comment] 2017-03-13 14:37
Thanks, I'll add it to my list. I plan to dig through all the source map issues filed (here and Bugzilla) once basic support is wired up.

**Comment by jasonLaster** [comment] 2017-03-13 16:11
closing this in favor of https://github.com/devtools-html/devtools-core/issues/246

**Closed by jasonLaster** 2017-03-13 16:11 UTC
Labels: bug, difficulty: hard, up for grabs

**Comment by tromey** [comment] 2017-05-31 16:33
The "no domain" text comes from the debugger, and happens because `getURL` is passed just the base name of the source, like "main.js".  So that part, at least, seems to be a debugger bug and not related to source maps.
