### ISSUE TITLE
[WatchExpressions] The debugger is wrongfully showing a watch expression as a source

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#3318] opened 2017-07-12 07:45 UTC
Steps to reproduce: 

1. Open the debugger
2. Add a watch expression (e.g. `yo`)
3. Open the console
4. Execute 
```js
{ 
  let x = [()=>{}]; 
  debugger; 
}
```

Expected result:
The debugger shows the following snippet in a tab
```js
{ 
  let x = [()=>{}]; 
  debugger; 
}
```

Actual result: 
The debugger shows the snippet briefly, and then the content of the watch expression (see GIF)
If you edit the watch expression, the tab content get's updated :)

![jul-12-2017 09-43-18](https://user-images.githubusercontent.com/578107/28107076-9a2dd004-66e6-11e7-964e-229f7a584a5e.gif)

This is visible in latest Nightly, I couldn't test against debugger's master

**Comment by jasonLaster** [comment] 2017-07-13 14:41
This is a dupe of #3329

**Closed** 2017-07-24 08:41 UTC
Labels: bug, in progress
