### ISSUE TITLE
Odd formatting for shortcuts in debugger tab on Windows 10

### ISSUE THREAD

**Issue by andreasbovens** [devtools-html/debugger.html#5201] opened 2018-01-25 19:19 UTC
When opening the debugger tab on Windows 10, I see the following:

![debugger-funky-font](https://user-images.githubusercontent.com/613077/35407335-8701cef0-0203-11e8-80be-31526804d9d3.png)

Two issues:
- the shortcuts and explanatory texts are not on the same line
- the shortcuts should probably not be in a monospace font

This issue does not occur on Mac.

**Comment by jasonLaster** [comment] 2018-01-30 23:13
Thanks @andreasbovens we'll look into it soon!

**Comment by jasonLaster** [comment] 2018-01-30 23:14
@ericawright this might be an easy fixup while you're in there :)

**Comment by jasonLaster** [comment] 2018-01-30 23:14
This is related to our discussions in #4928

**Comment by ericawright** [comment] 2018-02-07 19:21
<img width="250" alt="screen shot 2018-02-07 at 2 18 34 pm" src="https://user-images.githubusercontent.com/10803178/35936685-f0b075dc-0c11-11e8-8c55-0ef8c6046e58.png">
<img width="327" alt="screen shot 2018-02-07 at 2 18 52 pm" src="https://user-images.githubusercontent.com/10803178/35936688-f1bc3150-0c11-11e8-82ce-37e8994c4e13.png">
I can't seem to reproduce. 
Also, as for the monospaced font, the font it courier. @violasong would you like it to be something else? It looks good with mac's ⌘ and ⇧, we can use something different for win and Linux.

**Comment by jasonLaster** [comment] 2018-02-07 19:23
@ericawright could this be windows specific?

**Comment by ericawright** [comment] 2018-02-07 19:23
yes, I tested on windows, in a vm

**Comment by jasonLaster** [comment] 2018-02-07 19:26
cool. should we close this then if we can't repro?

**Comment by ericawright** [comment] 2018-02-07 19:30
nope, I realized that it can't be reproduced on the web app, but is reproducible in the debugger when attached to the browser

**Comment by ericawright** [comment] 2018-02-07 21:03
There seems to be a few things happening here. Courier font seems to align differently, so we have two fonts one aligns near the bottom and the other in the middle. I don't think it can be fixed unless we remove the two dividing divs, in order to align they both need to be in the same `<p>` but in different spans. 
The other thing, I noticed there is `.normal-layout` and `small-size-layout` classes in the welcomebox. The reason this is not showing up on mac, nor on the web-app launchpad, is that there is styling that seems to hide normal layout at all times 
WelcomBox.css line 30:
```
.welcomebox .normal-layout {
  display: none;
}
```
Then on line 66, we have a media query which once again hides `.normal-layout`, and shows `.small-size-layout`, but `.small-size-layout` had never actually been hidden.

So, it might just be worth removing the `.normal-layout` div entirely? We won't have that grid-like arrangement visually, but it seems we already don't have it.

**Comment by jasonLaster** [comment] 2018-02-07 21:09
hmm, i agree we need to simplify the dom. 

I wonder if we can get the grid with flexbox or another layout system?

**Comment by ericawright** [comment] 2018-02-07 21:10
Yeah, I was thinking of using grid or even a table to style it?

**Comment by jasonLaster** [comment] 2018-02-07 21:11
Also, i think chrome has a nice behavior here

![](http://g.recordit.co/fcDyIHVuR0.gif)

it's always fun to see how they do it: by popping the devtools out and opening another toolbox via cmd+option+i.

<img src='https://shipusercontent.com/12570649977057eeb4476c273d00980f/Screen%20Shot%202018-02-07%20at%204.09.48%20PM.png' title='Screen Shot 2018-02-07 at 4.09.48 PM.png' width=1440>

**Closed** 2018-02-11 14:32 UTC
Labels: bug
