### ISSUE TITLE
Debugger confused when breaking in some iframes

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#5814] opened 2018-03-29 08:27 UTC
Note: this was also failing with the old debugger so this might be a server bug rather than a client one.

See https://responsible-shelf.glitch.me/

The code is:
```html
<html>
    <body>
        <iframe></iframe>
        <script type="text/javascript">
            let src = `<button onclick="run()">click me</button>
                <script type="text/javascript">
                    function run() {
                        debugger;
                        console.log("hi");
                    }
                </s` + `cript>`;


            document.querySelector("iframe").contentDocument.write(src);
            document.querySelector("iframe").contentDocument.close();
        </script>
    </body>
</html>
```

When clicking on the button and therefore halting on "debugger", the debugger shows the source for the page, and is stopped on some random line of HTML.

![image](https://user-images.githubusercontent.com/1141550/38078072-67b8e02e-333b-11e8-8ec4-d24d5eb224d7.png)

In contrast Chrome's debugger is showing the following:
![image](https://user-images.githubusercontent.com/1141550/38078168-b107173c-333b-11e8-8709-f6ead1e10de2.png)

**Comment by jasonLaster** [comment] 2018-03-29 20:34
This is a cute way of creating dynamic scripts. This is a dupe of #4373. Dynamic scripts are poorly handled in the server, which I hope to fix once we remove the old debugger.

**Closed by jasonLaster** 2018-03-29 20:34 UTC
Labels: not-available
