### ISSUE TITLE
Debugger should stop React rendering while it is in background

### ISSUE THREAD

**Issue by ochameau** [devtools-html/debugger.html#5605] opened 2018-03-05 14:31 UTC
Console started doing that in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1399242) and more recently Netmonitor applied the same strategy in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1419350).
Console and Netmonitor converged into one shared helper module, via [this patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1443121). This helper is located in [devtools/client/shared/redux/visibility-handler-connect.js](https://hg.mozilla.org/integration/autoland/file/55b683e679b0/devtools/client/shared/redux/visibility-handler-connect.js).
In order to stop react rendering, you "just" have to replace your regular `connect` from redux, with the one provided by this module.

Now it is unclear to me how debugger.html can/should use such new m-c module.
This module may not be that useful when we run the debugger on launchpad. So using a mock, or using directly redux original `connect` method is an option.

**Comment by jasonLaster** [comment] 2018-03-05 22:49
closing as it's a duplicate of #4896

**Closed by jasonLaster** 2018-03-05 22:49 UTC
Labels: performance
