### ISSUE TITLE
Breakpoints - select breakpoint doesn't navigate in paused source

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#608] opened 2016-08-28 18:16 UTC
#### Steps to reproduce
* add a couple breakpoints in a source
* pause on one of the breakpoints
* select another breakpoint in the list in that source
* you won't be navigated to that source

This is probably due to the highlight line being there for the pause location

**Comment by jlongster** [comment] 2016-09-13 18:12
Will be fixed by #713

**Comment by jlongster** [comment] 2016-09-13 18:28
I'm pretty sure this is a dupe of #675

**Closed by jlongster** 2016-09-13 18:28 UTC
