### ISSUE TITLE
Watch Expressions pane is evaluating everything as "<not available>".

### ISSUE THREAD

**Issue by tommai78101** [devtools-html/debugger.html#2949] opened 2017-05-18 13:30 UTC
If you do the following, where you store all returned values into temporary variables:

![](http://i.imgur.com/l2QV1ZR.png)

And then add all of the temporary variables to the Watch Expressions pane, you will notice that everything being evaluated are all `"<not available>"`.

This includes `console.log()`, which is expected to return `undefined`. But it's actually returning `"<not available>"`.

More complete tests below:

![](http://i.imgur.com/pMyF4DR.png)

**Comment by sharathnarayanph** [comment] 2017-05-18 15:35
@jasonLaster I think the changes I made for "Formatting Reference Error" might have broke this. Let me check and keep you guys posted.

**Comment by jasonLaster** [comment] 2017-05-18 17:32
Thanks

**Comment by sharathnarayanph** [comment] 2017-05-25 15:02
@jasonLaster : I am not able to replicate this issue even after so many attempts. Not sure which corner case I am missing.  Any recommendation on how to proceed to replicate this?

**Comment by jasonLaster** [comment] 2017-06-05 03:05
Hey @tommai78101, mind putting together a small test case? A couple people have failed to reproduce this bug.

**Comment by tommai78101** [comment] 2017-06-05 09:58
Before I continue to attempt this, specifically, what FF dev edition version and branch are you all using? If multiple people cannot reproduce the issue, then it would most likely point to me not on the correct version, instead of the other way around.

I did specify it is on FF dev 54.0a2 stable, but I wondering if I should just find a way and update to the version you all are using/maintaining? Currently, I don't even know how to update to whatever version you all are using.

**Comment by tommai78101** [comment] 2017-06-05 13:12
Well, forget about this bug. FF Dev Edition Aurora branch was just updated to 54.0b12. Can't reproduce the bug nor create a special test case now. :+1:

**Comment by codehag** [comment] 2017-06-05 13:52
I will take a look to confirm if this is ok now

**Comment by codehag** [comment] 2017-06-06 09:11
This looks like it is fixed in the new FF Dev edition. If anyone has this issue again, feel free to comment.

**Closed by codehag** 2017-06-06 09:11 UTC
Labels: bug
