### ISSUE TITLE
Highlight and inspect DOM nodes

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/debugger.html#7067] opened 2018-09-28 14:09 UTC
One of the features in the old debugger UI was highlighting and inspecting DOM nodes. 

See this MDN page:
https://developer.mozilla.org/en-US/docs/Tools/Debugger_(Before_Firefox_52)/How_to/Highlight_and_inspect_DOM_nodes

If you hover over a DOM node in the Variables pane, it will be highlighted in the page. Also, a target icon will appear next to the variable. If you click on this target, the Inspector will open with this DOM element selected.

This is already supported in the Console panel - through Reps - and the Debugger should reuse it.

Honza

**Comment by jnachtigall** [comment] 2018-10-08 19:25
This is a dupe of #1427 which has a good comment on how this could be implemented:
https://github.com/devtools-html/debugger.html/issues/1427#issuecomment-305148382

**Comment by AnshulMalik** [comment] 2018-12-29 09:56
#7455 fixes this.

**Closed by AnshulMalik** 2018-12-29 09:56 UTC

**Comment by jnachtigall** [comment] 2018-12-29 14:44
As said in https://github.com/devtools-html/debugger.html/issues/7067#issue-364905282 above there was once a documentation about this feature at:

https://developer.mozilla.org/en-US/docs/Tools/Debugger_(Before_Firefox_52)/How_to/Highlight_and_inspect_DOM_nodes

which now gives a 404. 

I guess the docs have been removed. 

I think it should be readded under https://developer.mozilla.org/en-US/docs/Tools/Debugger#How_to where it was before. But unlike on bugzilla, I do not know how to add a `dev-docs-needed` (or similar) tag. @AnshulMalik or @darkwing  Any idea?

**Comment by nchevobbe** [comment] 2019-01-04 14:14
> As said in [#7067 (comment)](https://github.com/devtools-html/debugger.html/issues/7067#issue-364905282) above there was once a documentation about this feature at:
> 
> https://developer.mozilla.org/en-US/docs/Tools/Debugger_(Before_Firefox_52)/How_to/Highlight_and_inspect_DOM_nodes
> 
> which now gives a 404.
> 
> I guess the docs have been removed.
> 
> I think it should be readded under https://developer.mozilla.org/en-US/docs/Tools/Debugger#How_to where it was before. But unlike on bugzilla, I do not know how to add a `dev-docs-needed` (or similar) tag. @AnshulMalik or @darkwing Any idea?

I transfered this to the MDN team, this will be handled soon :)

**Comment by irenesmith** [comment] 2019-02-26 08:13
Checked on this and the highlight is not working. I will keep an eye on the state of this and document it when it is working.

**Comment by nchevobbe** [comment] 2019-02-26 08:18
Filed https://github.com/firefox-devtools/debugger/issues/8032 for highlighting
