### ISSUE TITLE
[Editor] scrolls on click after switching to the console

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5497] opened 2018-02-21 21:49 UTC
1. Open a tall JS file in the debugger, scroll down a bit.
2. Switch to the console and enter something
3. Switch back to the debugger, the scroll position has been preserved
4. Click in the source area

Result: the debugger scrolls

![screencast](https://user-images.githubusercontent.com/7477678/36507228-5edda226-1759-11e8-8536-cf4afd1de45c.gif)

**Comment by jasonLaster** [comment] 2018-02-27 15:10
This is similar to #4852

**Comment by jasonLaster** [comment] 2018-03-07 13:46
closing it as it's a dupe of #4852

**Closed by jasonLaster** 2018-03-07 13:46 UTC
Labels: bug, help wanted
