### ISSUE TITLE
[Stepping] Debugger occasionally switches to line with large number

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#5069] opened 2018-01-10 14:56 UTC
Bugzilla related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1326834

Todo: confirm if this is still happening

STR_1:
1. Open attached "testcase 1"
2. Open debugger, set breakpoint in script at line 2
3. Click on the page content
4. Click "Step In" in debugger

AR:  Debugger switches to line "/* we need a miracle */"
     More generally, it scrolls current script to the very end, as it tries to go to line 3857049061

ER:  Debugger should swith to line with "if" or to line with closing bracket of current function

Note: 
 It's not clear what component it is. Is it possible that JS engine reports something wrong that
 confuses debugger? Or probably debugger itself should be updated to handle this properly.
 I can't possibly know, because I don't do the development.

This is regression from bug 1261826. Regression range:
> https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=a7f37ab1e0c3bcd5f43bcadf1b8e6a69abf86f17&tochange=2e29695fee8730d8dae52960dc98ff7ade38aacb

**Comment by jasonLaster** [comment] 2018-01-16 15:04
Closing as I could not reproduce it:

![](http://g.recordit.co/ShptxrkZhJ.gif)

**Closed by jasonLaster** 2018-01-16 15:04 UTC
Labels: bug, not-available
