### ISSUE TITLE
watched variables that are not in scope crashes debugguer

### ISSUE THREAD

**Issue by Anzumana** [devtools-html/debugger.html#3997] opened 2017-09-13 14:37 UTC
I was serving a lot of different website locally. ( eg. localhost/wwwFolder   localhost/wwwAnotherFolder)
and defined some watch expressions.
when i go to  a different locally served website the watch expressions of the old page persist and cause the debugger then to crash as certain values will not be there and property access expressions fail.
tested same in chrome for reference and they seem to handle the error silently.
they display <not available > just like we do.

My guess would be that we check the domain to figure our which watch expressions should get restored for which page. and since both sites are on the same domain that logic should work.

**Comment by jasonLaster** [comment] 2017-09-13 14:39
Thanks for filing, I think this is a dupe of #3997. 

You should see if there is a fix in `actions/expressions`!

**Comment by Anzumana** [comment] 2017-09-15 09:00
i guess you mean another issue as 3997 is this issue :)

**Comment by jasonLaster** [comment] 2017-09-15 13:49
yep #3597 :)

**Comment by jasonLaster** [comment] 2017-09-22 23:11
fixed!

**Closed by jasonLaster** 2017-09-22 23:11 UTC
