### ISSUE TITLE
[Breakpoint] the pending breakpoints pref is using too much memory

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5219] opened 2018-01-27 16:24 UTC
In tabs where the debugger is loaded, each time I enter something to the web console, the browser console shows

> Warning: attempting to write 24821 bytes to preference devtools.debugger.pending-breakpoints. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.

**Comment by Loirooriol** [comment] 2018-01-27 17:53
If there is so much data it's because I have some breakpoints like

```
  "https://c.s-microsoft.com/en-us/CMSScripts/script.jsx?k=0502864a-b6ef-2f14-9f8e-267004d3a4e0_c5ea3348-55af-729a-2641-14f0312bacf3_742bd11f-3d7c-9955-3df5-f02b66689699_525283c5-3d35-4dd2-5a96-acaf933fab61_49488e0d-6ae2-5101-c995-f4d56443b1d8_7dea7b90-4334-c043-b252-9f132d19ee19_38aa9ffb-ddb5-75be-6536-a58628f435f5_e3e65a0a-c133-43e7-571d-2293e03f85e6_4ca0e9dc-a4de-17ba-f0de-d1d346cb99e2_06310cd8-41c6-3b11-4645-b4884789ed70_5c27e8aa-9347-969e-39ac-37a4de428a8d_d6872b5a-5310-a73c-7cb3-227a3213a1c5_be92d794-4118-193f-9871-58b72092a5ac_64c742e2-b29c-b6c1-fdd9-accf33ec40bd_cf2ceca9-3467-a5b3-d095-68958eee6d4c_cec39dd8-f1d3-56f1-abfc-a7db34ff7b46_ec5fa2c9-3950-ff57-a5c3-1fa77e0db190_d19f9592-65df-bcc9-e30e-439b875c3381_76a3d06f-f11f-77ef-9bfd-6227ba750200_5e1caa45-461c-3b04-f88b-8cd50af16db5_c2dceda8-20b4-7d3f-13b6-9cac67d7df17_914fa41b-cc86-d3b0-4e15-2fdfa357bcc7_40c6c884-da6e-7c2c-081f-4a7dfe7c7245_35f9df4f-1b4f-752c-4522-e2f2a8d2a77f_dd708766-2c4c-f068-79b0-121081b8621c_a5201e55-aa32-d778-3300-0a557fd39f8c_26d1ef17-d0f5-2db9-fe2d-ced935bb409f_dec1e610-d5a5-8c25-bf7e-9c0668c9c4a7_ef37e36f-3037-c8f0-eaa1-a5f4a643fc0d_614dbc76-bfb6-0db6-ecfc-db7c5d4956b2_1fa77585-d5dc-d975-bd87-48d017a6c87e:formatted:4613:": {
    "condition": null,
    "disabled": true,
    "location": {
      "sourceUrl": "https://c.s-microsoft.com/en-us/CMSScripts/script.jsx?k=0502864a-b6ef-2f14-9f8e-267004d3a4e0_c5ea3348-55af-729a-2641-14f0312bacf3_742bd11f-3d7c-9955-3df5-f02b66689699_525283c5-3d35-4dd2-5a96-acaf933fab61_49488e0d-6ae2-5101-c995-f4d56443b1d8_7dea7b90-4334-c043-b252-9f132d19ee19_38aa9ffb-ddb5-75be-6536-a58628f435f5_e3e65a0a-c133-43e7-571d-2293e03f85e6_4ca0e9dc-a4de-17ba-f0de-d1d346cb99e2_06310cd8-41c6-3b11-4645-b4884789ed70_5c27e8aa-9347-969e-39ac-37a4de428a8d_d6872b5a-5310-a73c-7cb3-227a3213a1c5_be92d794-4118-193f-9871-58b72092a5ac_64c742e2-b29c-b6c1-fdd9-accf33ec40bd_cf2ceca9-3467-a5b3-d095-68958eee6d4c_cec39dd8-f1d3-56f1-abfc-a7db34ff7b46_ec5fa2c9-3950-ff57-a5c3-1fa77e0db190_d19f9592-65df-bcc9-e30e-439b875c3381_76a3d06f-f11f-77ef-9bfd-6227ba750200_5e1caa45-461c-3b04-f88b-8cd50af16db5_c2dceda8-20b4-7d3f-13b6-9cac67d7df17_914fa41b-cc86-d3b0-4e15-2fdfa357bcc7_40c6c884-da6e-7c2c-081f-4a7dfe7c7245_35f9df4f-1b4f-752c-4522-e2f2a8d2a77f_dd708766-2c4c-f068-79b0-121081b8621c_a5201e55-aa32-d778-3300-0a557fd39f8c_26d1ef17-d0f5-2db9-fe2d-ced935bb409f_dec1e610-d5a5-8c25-bf7e-9c0668c9c4a7_ef37e36f-3037-c8f0-eaa1-a5f4a643fc0d_614dbc76-bfb6-0db6-ecfc-db7c5d4956b2_1fa77585-d5dc-d975-bd87-48d017a6c87e:formatted",
      "line": 4613,
      "column": 0
    },
    "astLocation": {
      "offset": {
        "sourceId": "server1.conn1.child1/source177/originalSource-ee85e42e85b19bff3a1cab6a06265ede",
        "sourceUrl": "https://c.s-microsoft.com/en-us/CMSScripts/script.jsx?k=0502864a-b6ef-2f14-9f8e-267004d3a4e0_c5ea3348-55af-729a-2641-14f0312bacf3_742bd11f-3d7c-9955-3df5-f02b66689699_525283c5-3d35-4dd2-5a96-acaf933fab61_49488e0d-6ae2-5101-c995-f4d56443b1d8_7dea7b90-4334-c043-b252-9f132d19ee19_38aa9ffb-ddb5-75be-6536-a58628f435f5_e3e65a0a-c133-43e7-571d-2293e03f85e6_4ca0e9dc-a4de-17ba-f0de-d1d346cb99e2_06310cd8-41c6-3b11-4645-b4884789ed70_5c27e8aa-9347-969e-39ac-37a4de428a8d_d6872b5a-5310-a73c-7cb3-227a3213a1c5_be92d794-4118-193f-9871-58b72092a5ac_64c742e2-b29c-b6c1-fdd9-accf33ec40bd_cf2ceca9-3467-a5b3-d095-68958eee6d4c_cec39dd8-f1d3-56f1-abfc-a7db34ff7b46_ec5fa2c9-3950-ff57-a5c3-1fa77e0db190_d19f9592-65df-bcc9-e30e-439b875c3381_76a3d06f-f11f-77ef-9bfd-6227ba750200_5e1caa45-461c-3b04-f88b-8cd50af16db5_c2dceda8-20b4-7d3f-13b6-9cac67d7df17_914fa41b-cc86-d3b0-4e15-2fdfa357bcc7_40c6c884-da6e-7c2c-081f-4a7dfe7c7245_35f9df4f-1b4f-752c-4522-e2f2a8d2a77f_dd708766-2c4c-f068-79b0-121081b8621c_a5201e55-aa32-d778-3300-0a557fd39f8c_26d1ef17-d0f5-2db9-fe2d-ced935bb409f_dec1e610-d5a5-8c25-bf7e-9c0668c9c4a7_ef37e36f-3037-c8f0-eaa1-a5f4a643fc0d_614dbc76-bfb6-0db6-ecfc-db7c5d4956b2_1fa77585-d5dc-d975-bd87-48d017a6c87e:formatted",
        "line": 4613,
        "column": 0
      }
    },
    "generatedLocation": {
      "sourceUrl": "https://c.s-microsoft.com/en-us/CMSScripts/script.jsx?k=0502864a-b6ef-2f14-9f8e-267004d3a4e0_c5ea3348-55af-729a-2641-14f0312bacf3_742bd11f-3d7c-9955-3df5-f02b66689699_525283c5-3d35-4dd2-5a96-acaf933fab61_49488e0d-6ae2-5101-c995-f4d56443b1d8_7dea7b90-4334-c043-b252-9f132d19ee19_38aa9ffb-ddb5-75be-6536-a58628f435f5_e3e65a0a-c133-43e7-571d-2293e03f85e6_4ca0e9dc-a4de-17ba-f0de-d1d346cb99e2_06310cd8-41c6-3b11-4645-b4884789ed70_5c27e8aa-9347-969e-39ac-37a4de428a8d_d6872b5a-5310-a73c-7cb3-227a3213a1c5_be92d794-4118-193f-9871-58b72092a5ac_64c742e2-b29c-b6c1-fdd9-accf33ec40bd_cf2ceca9-3467-a5b3-d095-68958eee6d4c_cec39dd8-f1d3-56f1-abfc-a7db34ff7b46_ec5fa2c9-3950-ff57-a5c3-1fa77e0db190_d19f9592-65df-bcc9-e30e-439b875c3381_76a3d06f-f11f-77ef-9bfd-6227ba750200_5e1caa45-461c-3b04-f88b-8cd50af16db5_c2dceda8-20b4-7d3f-13b6-9cac67d7df17_914fa41b-cc86-d3b0-4e15-2fdfa357bcc7_40c6c884-da6e-7c2c-081f-4a7dfe7c7245_35f9df4f-1b4f-752c-4522-e2f2a8d2a77f_dd708766-2c4c-f068-79b0-121081b8621c_a5201e55-aa32-d778-3300-0a557fd39f8c_26d1ef17-d0f5-2db9-fe2d-ced935bb409f_dec1e610-d5a5-8c25-bf7e-9c0668c9c4a7_ef37e36f-3037-c8f0-eaa1-a5f4a643fc0d_614dbc76-bfb6-0db6-ecfc-db7c5d4956b2_1fa77585-d5dc-d975-bd87-48d017a6c87e",
      "line": 1,
      "column": 141315
    }
  }
```

Consider compressing the JSON before storing it or something like that.

**Comment by jasonLaster** [comment] 2018-01-27 21:40
thanks. That's a good short term idea - for instance sourceUrl is repeated quite a bit.

I think we should also look at other storage options.

**Comment by lukaszsobek** [comment] 2018-01-28 07:27
@jasonLaster If the only thing we are doing with the location is adding `:formatted` `:line` and `:column` we might consider rearranging the format to something like:

```
{
"sourceUrl": "https://c.s-microsoft.com/en-us/CMSScripts/script.jsx?k=050286...",
"params: { "condition": null, "disabled": true ... },
"location": { "line": 4613, "column": 0 },
"astLocation": {
        "sourceId": "server1.conn1.child1/source177/originalSource-ee85e...",
        "line": 4613,
        "column": 0
 },
"generatedLocation": { "line": 1, "column": 141315  }
  }
```

**Comment by jasonLaster** [comment] 2018-06-19 03:15
@mlissner could you share a screenshot of what you see?

**Comment by mlissner** [comment] 2018-07-11 22:39
@jasonLaster Sorry, it's long gone. I'll try to catch it if it crops up again.

**Comment by jasonLaster** [comment] 2018-07-12 01:42
Thanks @mlissner 

By the way, after talking with several folks it looks like indexed-db is the way to go.

**Comment by jasonLaster** [comment] 2018-07-25 13:20
This is a dupe of #6279

**Closed by jasonLaster** 2018-07-25 13:20 UTC
Labels: performance
