### ISSUE TITLE
Show a variables view inspection popup on mouse hover

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#1293] opened 2016-11-23 09:52 UTC
Since upgrading to FDE 52 I am missing the ability to hover over a variable and have its properties in a popup. I know there's already `Scopes` pane at right bottom but this is some way and clicks away and just takes longer.

In case you want to implement this, it would be great if the popup would be transient :) Same way Chrome Debugger or most IDEs do it: https://bugzilla.mozilla.org/show_bug.cgi?id=943341

**Comment by clarkbw** [comment] 2016-11-23 16:32
Thanks for filing this!  We plan on getting this feature added back to the debugger and I agree that a transient popup would be the right thing.  The only gotcha there is to make sure the move movement wasn't toward the popup itself.

This was the old variables view code: https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/views/variable-bubble-view.js

**Comment by jasonLaster** [comment] 2016-11-23 20:03
Thanks @jnachtigall. I'm closing this as it's a dupe of #626.

**Closed by jasonLaster** 2016-11-23 20:03 UTC

**Comment by SebastianZ** [comment] 2017-01-23 13:07
Issue #1574 is now obviously used to reimplement this feature.

Sebastian
