### ISSUE TITLE
[CommandBar] Fix height when paused in chrome

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1882] opened 2017-01-30 15:39 UTC
When the debugger is paused the height of the command bar is too short in chrome (firefox is fine).  

**not paused**
![screen shot 2017-01-30 at 10 38 22 am](https://cloud.githubusercontent.com/assets/254562/22429372/5de95e6c-e6d8-11e6-8058-0b31497c3d42.png)

**paused**
![screen shot 2017-01-30 at 10 36 32 am](https://cloud.githubusercontent.com/assets/254562/22429373/5deb7864-e6d8-11e6-8944-d50fcbb1ffd7.png)

**Comment by jasonLaster** [comment] 2017-01-30 15:40
@irfanhudda interested in looking at this?

**Comment by Garbee** [comment] 2017-01-30 15:41
This is not reproducing on Linux for me. So the rendering seems OS-specific.

**Comment by jasonLaster** [comment] 2017-01-30 15:43
@Garbee great find:

![screen shot 2017-01-30 at 10 42 36 am](https://cloud.githubusercontent.com/assets/254562/22429512/dbe1c7e6-e6d8-11e6-8349-bb4c5faa89d9.png)

**Comment by Garbee** [comment] 2017-01-30 16:03
If it's Chrome-only then I think I know what the problem is relating to. I'll peek at it (since I am the one that caused this) once I've figured out something for this postmerge script problem.

**Comment by irfanhudda** [comment] 2017-01-30 16:05
@Garbee Not sure if this helps but I could not reproduce this in chromium(debian).

**Comment by Garbee** [comment] 2017-01-30 16:06
That helps. As it means it isn't *Chrome* related but *Chrome on Mac OS*. Which means I can't test that myself.

Someone with a Mac specifically will need to triage this. I should be able to backtrace a minimal report from whatever the fixing patch is for the Blink team to look at to fix their engine.

**Comment by clarkbw** [comment] 2017-01-30 18:23
I'm seeing this on Mac.  If I change `display: flex` for the command bar to `display: block` then the problem goes away.

**Comment by Garbee** [comment] 2017-01-31 13:40
I have this reproducing now. It depends on the *height* of the viewport due to the SecondaryPanel being a `flex` container as well. Working on getting the right solution in place now.

**Comment by Garbee** [comment] 2017-01-31 15:59
This is fixed now.

**Closed** 2017-02-01 18:01 UTC
Labels: design, difficulty: medium, up for grabs
