### ISSUE TITLE
npm install fails due to non-existant dependencies?

### ISSUE THREAD

**Issue by apollo13** [devtools-html/debugger.html#742] opened 2016-09-15 08:16 UTC
```
npm install
npm WARN deprecated babel@6.5.2: Babel's CLI commands have been moved from the babel package to the babel-cli package
npm WARN deprecated babel-plugin-module-alias@1.6.0: WARNING: This project has been renamed to babel-plugin-module-resolver. Install babel-plugin-module-resolver for new features
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'kadira/storybook' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'debugger.html'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.7.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "-G" "install"
npm ERR! cwd /home/florian/sources/debugger.html
npm ERR! node -v v4.4.7
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/florian/sources/debugger.html/npm-debug.log
npm ERR! not ok code 0
```

`npm start` subsequently throws:
```
> debugger.html@0.0.5 start /home/florian/sources/debugger.html
> node bin/development-server

module.js:327
    throw err;
    ^

Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/florian/sources/debugger.html/bin/development-server.js:5:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! debugger.html@0.0.5 start: `node bin/development-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the debugger.html@0.0.5 start script.
npm ERR! This is most likely a problem with the debugger.html package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/development-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls debugger.html
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.7.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/florian/sources/debugger.html
npm ERR! node -v v4.4.7
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/florian/sources/debugger.html/npm-debug.log
npm ERR! not ok code 0

```

**Comment by jlongster** [comment] 2016-09-15 13:29
It looks like the storybook install steps have changes. Thanks for filing, we will fix.

**Comment by jasonLaster** [comment] 2016-09-15 15:05
We've seen this issue before as well

https://github.com/devtools-html/debugger.html/issues/240

looks like their new install steps are:
```
npm i -g getstorybook
cd my-react-app
getstorybook
```

**Comment by clarkbw** [comment] 2016-09-20 23:00
I can't reproduce this on new installs.  It looks like this issue https://github.com/kadirahq/react-storybook/issues/15 which is usually about using an npm mirror.

**Comment by jasonLaster** [comment] 2016-09-20 23:02
Hmm, let me switch the storybook step out. Having a seamless install, getting started experience is important for the contributor [funnel](https://qph.ec.quoracdn.net/main-qimg-75afe1307fc3d04c84b6b19853fcbf2b?convert_to_webp=true).

**Comment by apollo13** [comment] 2016-09-21 06:44
@clarkbw I was not using any mirror (I think, I am relatively new to npm ;))

**Comment by clarkbw** [comment] 2016-09-21 15:17
@apollo13 thanks for reporting this!  @jasonLaster is working on a fix in #789 hopefully this will be resolved soon.

**Comment by jasonLaster** [comment] 2016-09-21 16:08
@apollo13 no worries. actually the mirror comes in from the npm side. NPM uses a mirror when the the dep is `@org/something`, which makes it flakey.

**Comment by jasonLaster** [comment] 2016-10-19 19:47
Closing this as storybook is no longer a dependency

**Closed by jasonLaster** 2016-10-19 19:47 UTC
Labels: infrastructure
