### ISSUE TITLE
cmd+f should open file search if there are no open files

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#1752] opened 2017-01-19 00:13 UTC
[bug 1319431](https://bugzilla.mozilla.org/show_bug.cgi?id=1319431)

Steps to reproduce:

1. Open example.com in a new tab
2. Open the new debugger in the devtools toolbox
3. Hit ctrl-f
( find in page content search appears instead of debugger search )

The old debugger used to capture the cmd+f shortcut and redirect it to the search.  We should enable that again.

Additionally I've noticed that Chrome file search is also bound to cmd+O (Open) which might be something to add as well.

**Comment by jasonLaster** [comment] 2017-01-19 03:36
hmm, I think `cmd+O` makes sense. 

I'm not sure about `cmd-f`, in atom it opens file search which is a no-op :P

**Comment by clarkbw** [comment] 2017-01-19 04:08
> I'm not sure about cmd-f, in atom it opens file search which is a no-op :P

Yeah, I agree.  We show exactly what key command is required in the UI.

**Comment by clarkbw** [comment] 2017-01-19 04:17
> Ideally I think the debugger should always capture ctrl-f if it uses it sometimes.  If you're not in the right mode it should display "select a file or use ctrl-p to search file names" or something.

The only other thing to think about is that Ben asks that we at least always capture the cmd+f shortcut so that focus doesn't bump to the default content option.

**Comment by jnachtigall** [comment] 2017-01-19 08:56
This very similar to https://github.com/devtools-html/debugger.html/issues/1376#issuecomment-266974238 (which was closed - I think due to a misunderstanding and it's gone under the radar - but, anyway, it's still a valid bug in Nightly 53.0a1 (2017-01-18). Just tested now)

**Comment by clarkbw** [comment] 2017-01-19 16:04
It sounds reasonable to me to capture `cmd+f` and do a no-op to at least prevent the default from happening.   I can re-work this issue to reflect that.

**Comment by jasonLaster** [comment] 2017-01-27 16:58
closing this and opening a small actionable issue

**Closed by jasonLaster** 2017-01-27 16:58 UTC

**Comment by jasonLaster** [comment] 2017-01-27 17:01
actually, i can't reproduce on nightly, so not re-opening.

**Comment by jnachtigall** [comment] 2017-01-27 20:46
Interesting. I also just retested on Nightly 54 (Linux) and it's working now. I guess the recent search improvements fixed this too :thumbs-up:
