### ISSUE TITLE
[Scopes] Improve object bucketing

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#2144] opened 2017-02-25 00:24 UTC
It might be nice if the bucketing strategy for the ObjectInspector could prioritize certain properties to not be bucketed such that instead of a list of all buckets we could pull out certain elements. 

For example with the Window object we could pull the non-default properties out to the top instead of leaving them inside the buckets where you have to look for them.
![screen shot 2017-02-24 at 4 22 04 pm](https://cloud.githubusercontent.com/assets/2134/23325870/7ed66640-faad-11e6-9bac-0d9157de7a19.png)

**Comment by jasonLaster** [comment] 2017-02-25 01:42
Hmm, that's nice. Our window would look something like this

```
window
  - appStore: Object
  - client: Object
  - [default properties]
  - __proto__: WindowPrototype
```

**Comment by clarkbw** [comment] 2017-02-25 02:08
Exactly!

**Comment by jasonLaster** [comment] 2017-03-07 14:24
dlosing as it's a dupe of #2280

**Closed by jasonLaster** 2017-03-07 14:24 UTC
Labels: enhancement
