### ISSUE TITLE
Webpack path in tabs doesn't make sense

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#6951] opened 2018-09-07 16:37 UTC
STR:
- Open Debugger on https://belen-albeza.github.io/webcomponents-examples/wc-vue.html
- Open some XUser files

AR: `…////…` paths in tabs
ER: Something meaningful or nothing as it is in the root.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/8599/45231637-78157e80-b281-11e8-8a85-130e44dc840e.png">

**Comment by digitarald** [comment] 2018-09-07 16:42
@darkwing Jason told me to ping you 👋🏻 as this might be known or intentional

**Comment by darkwing** [comment] 2018-09-07 16:55
Closing as duplicate of 6790

**Closed** 2018-09-21 12:31 UTC
Labels: bug
