### ISSUE TITLE
Stepping should keep the "expand" state for the scopes

### ISSUE THREAD

**Issue by julienw** [devtools-html/debugger.html#5728] opened 2018-03-20 10:35 UTC
When debugging, this is usual that we "expand" the scopes to better see some variables we want to follow. But stepping resets the scopes view to its initial view. This is painful.

**Comment by jasonLaster** [comment] 2018-03-20 12:34
This is a dupe of #3269.

I'd like to get to this in the next couple of months.

**Closed by jasonLaster** 2018-03-20 12:34 UTC
Labels: not-available
