### ISSUE TITLE
[Breakpoint] Conditional Breakpoint Editing Does Not Save

### ISSUE THREAD

**Issue by Enether** [devtools-html/debugger.html#5431] opened 2018-02-15 09:52 UTC
## Steps to reproduce:

1. Set a conditional breakpoint
2. Right click it - Click "Edit Breakpoint"
3. Type something else and press enter
You will see that the original condition breakpoint is the same

**Comment by mmcote** [comment] 2018-02-15 15:52
Hello @Enether, I was just wondering if you would be able to give me any more information to reproduce this bug. So far I haven't been able to reproduce with the latest build. Attached is just a gif me switching the conditional statement and then testing that it has been changed and the condition does work after.

![feb-15-2018 08-49-01](https://user-images.githubusercontent.com/14250545/36265821-477437c0-122d-11e8-99a1-872ce40e22dd.gif)

**Comment by AnshulMalik** [comment] 2018-02-20 16:56
Can't reproduce this either. Could you provide us with some more info? @Enether

**Comment by nyrosmith** [comment] 2018-02-23 19:18
I'll close this for now. Feel free to reopen when this happens again or can be reproduced

**Closed by nyrosmith** 2018-02-23 19:18 UTC
Labels: bug, not-available
