### ISSUE TITLE
Breakpoint line not in view when paused

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/debugger.html#6375] opened 2018-05-21 22:19 UTC
This STR may not reproduce, I'm not sure, but this has happened to me a few times now so I'm filing it:

STR:
 * Add a debugger statement to some code in perf.html.
 * Trigger the code to catch on that statement.

Actual Result:
<img width="655" alt="image" src="https://user-images.githubusercontent.com/1588648/40332717-b58e47ae-5d1a-11e8-9776-8c3de4a479e6.png">

Expected Result:
<img width="655" alt="image" src="https://user-images.githubusercontent.com/1588648/40332787-01f0f7ea-5d1b-11e8-980d-36ca030115e6.png">

**Comment by jasonLaster** [comment] 2018-05-22 13:10
I believe this is a dupe of #6353

**Closed by jasonLaster** 2018-05-22 13:10 UTC
Labels: not-available
