### ISSUE TITLE
Symbol Search does not auto scroll 

### ISSUE THREAD

**Issue by AnshulMalik** [devtools-html/debugger.html#4842] opened 2017-12-01 15:09 UTC
![bug](https://user-images.githubusercontent.com/7821757/33488668-5d66316e-d6d7-11e7-99da-e937b2222448.gif)

**Expected Behaviour**
Selected row should remain in viewport.

**Comment by lukaszsobek** [comment] 2017-12-09 11:32
Duplicate of #4504

**Closed by lukaszsobek** 2017-12-09 11:32 UTC
Labels: bug, not-available
