### ISSUE TITLE
[console] link does not select location when debugger is closed

### ISSUE THREAD

**Issue by bzbarsky** [devtools-html/debugger.html#3411] opened 2017-07-21 19:02 UTC
I filed this as https://bugzilla.mozilla.org/show_bug.cgi?id=1383209 because I can attach files there, but since I'm not sure anyone is looking at bugs reported there...

**Comment by jasonLaster** [comment] 2017-07-21 19:13
Thanks for filing

---

STEPS TO REPRODUCE:

1)  Load the testcase I'm about to attach in a clean profile.
2)  Cmd+Option+K to open the console.
3)  Click the link on the "ReferenceError" line (linking to line 1201 of the JS file).

ACTUAL RESULTS: Debugger opens, loads JS file, does NOT scroll to the line.

EXPECTED RESULTS: Scroll to the line and select it.  This works fine with the old debugger frontend.

ADDITIONAL INFORMATION: If the debugger is already open when loading the testcase, then scrolling to the line does work, but it doesn't get highlighted (unlike with the old debugger frontend).

This bug makes debugging errors really annoying.

**Comment by codehag** [comment] 2017-07-24 11:24
In the `next` branch, we have a new issue -- the debugger is not opened, and instead opens a new tab with the source and the correct line highlighted (just like the old debugger)

**Comment by codehag** [comment] 2017-07-24 11:43
Not sure if I am going in the right direction, but when I test the str, i sometimes get the new tab behavior and the following error:

```
*************************
A coding exception was thrown in a Promise resolution callback.
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full message: TypeError: this._extraPools is null
Full stack: addActorPool@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/main.js:1540:5
get threadLifetimePool@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/script.js:498:7
onSource/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/source.js:493:11
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922:23
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:806:7
Promise*scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:739:11
schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:770:7
completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:707:7
onResponse@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/DevToolsUtils.js:480:7
onStopRequest@resource://gre/modules/NetUtil.jsm:131:17

*************************
console.error:
  Message: Error: Could not load the source for https://bug1383209.bmoattachments.org/attachment.cgi?id=8888882.
TypeError: this._extraPools is null
Stack: addActorPool@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/main.js:1540:5
get threadLifetimePool@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/script.js:498:7
onSource/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/source.js:493:11
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922:23
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:806:7
Promise*scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:739:11
schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:770:7
completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:707:7
onResponse@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/DevToolsUtils.js:480:7
onStopRequest@resource://gre/modules/NetUtil.jsm:131:17
Line: 1540, column: 5
  Stack:
    onSource/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/source.js:500:15
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:925:21
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:806:7
Promise*scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:739:11
schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:770:7
completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:707:7
onResponse@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/DevToolsUtils.js:480:7
onStopRequest@resource://gre/modules/NetUtil.jsm:131:17

onSource/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/source.js:500:15
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:925:21
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:806:7
Promise*scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:739:11
schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:770:7
completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:707:7
onResponse@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/DevToolsUtils.js:480:7
onStopRequest@resource://gre/modules/NetUtil.jsm:131:17
```

**Comment by codehag** [comment] 2017-07-24 11:49
Not sure if I am going in the right direction, but when I test the str, i sometimes get the new tab behavior and the following error:
```
*************************
A coding exception was thrown in a Promise resolution callback.
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full message: TypeError: this._extraPools is null
Full stack: addActorPool@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/main.js:1540:5
get threadLifetimePool@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/script.js:498:7
onSource/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/source.js:493:11
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922:23
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:806:7
Promise*scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:739:11
schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:770:7
completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:707:7
onResponse@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/DevToolsUtils.js:480:7
onStopRequest@resource://gre/modules/NetUtil.jsm:131:17

*************************
console.error:
  Message: Error: Could not load the source for https://bug1383209.bmoattachments.org/attachment.cgi?id=8888882.
TypeError: this._extraPools is null
Stack: addActorPool@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/main.js:1540:5
get threadLifetimePool@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/script.js:498:7
onSource/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/source.js:493:11
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:922:23
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:806:7
Promise*scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:739:11
schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:770:7
completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:707:7
onResponse@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/DevToolsUtils.js:480:7
onStopRequest@resource://gre/modules/NetUtil.jsm:131:17
Line: 1540, column: 5
  Stack:
    onSource/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/source.js:500:15
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:925:21
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:806:7
Promise*scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:739:11
schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:770:7
completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:707:7
onResponse@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/DevToolsUtils.js:480:7
onStopRequest@resource://gre/modules/NetUtil.jsm:131:17

onSource/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/source.js:500:15
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:925:21
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:806:7
Promise*scheduleWalkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:739:11
schedulePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:770:7
completePromise@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:707:7
onResponse@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/DevToolsUtils.js:480:7
onStopRequest@resource://gre/modules/NetUtil.jsm:131:17
```

**Comment by codehag** [comment] 2017-07-24 14:11
some more debug info: when I get verbose logs for the debugger I get the following just before i get redirect to viewsource:

```
DBG-SERVER: Packet 319 sent from "server1.conn0.consoleActor2"
DBG-SERVER: Received packet 319: {
  "from": "server1.conn0.consoleActor2",
  "type": "pageError",
  "pageError": {
    "errorMessage": "Property contained reference to invalid variable.  Error in parsing value for ‘height’.  Falling back to ‘initial’.",
    "errorMessageName": "",
    "sourceName": "resource://devtools/client/debugger/new/debugger.css",
    "lineText": " var(--editor-footer-height)",
    "lineNumber": 1450,
    "columnNumber": 28403,
    "category": "CSS Parser",
    "timeStamp": 1500905369044,
    "warning": true,
    "error": false,
    "exception": false,
    "strict": false,
    "info": false,
    "private": false,
    "stacktrace": null,
    "notes": null
  }
}
```

**Comment by bzbarsky** [comment] 2017-07-24 15:15
I did encounter the view-source behavior once when I was playing around with this stuff...  So it's not just you, fwiw.  ;)

**Comment by jasonLaster** [comment] 2017-07-25 16:53
we can handle the view-source bug in another issue. The debugger should now scroll to the correct location every time

**Comment by jasonLaster** [comment] 2017-09-15 13:44
re-opening because i no longer see the issue

**Comment by jasonLaster** [comment] 2018-03-12 21:51
When i tested this today, it opened view-source, which was strange

**Comment by darkwing** [comment] 2019-01-29 22:58
Retested and is working as it should, scrolling to line.  Closing.

**Closed by darkwing** 2019-01-29 22:58 UTC
Labels: bug: P1
