### ISSUE TITLE
Debugging Angular 2+ is very painful

### ISSUE THREAD

**Issue by usmanibnesadiq** [devtools-html/debugger.html#5132] opened 2018-01-17 22:30 UTC
Hi, I have been trying to switch to Firefox as my primary browser since nightly versions of Quantum. Debugging a plain vanilla Angular CLI project in FF Q is extremely painful. Here are the key issues:

1- The debugger tab is mostly empty when loading the page first time. Say you have a "debugger" statement in a JS/TS file and you open dev tools by pressing F12. You get a notification saying, the debugger is paused..." but when you go to debugger tab, there is nothing to be seen. It takes at least 30 seconds to show up the javascript (from source maps) and even then when you try to step over/through, there is no evaluation on variable values, stepping over takes 3-5 seconds on average.

2- The source maps are not loaded by default. You have to go to sources, find the file and manually set breakpoints.

3- There is no variable value evaluation even after putting your cursor on an executed line of code.

4- The watch values you have added, never keep their state. For example, if you had added a complex object and it was expanded, the next time its value is evaluated, it is collapsed again.

All these issues don't exist at all in Chrome. It is lightening fast to debug, display variable values in line, loading source maps and what not. To reproduce all these issues, you can create a vanilla new Angular app using Angular CLI and see how it goes. I have tried FF Stable, Dev, Beta and Nightly (all latest versions) but the issue is there on all editions.

Hope you guys can fix it and help me get rid of Chrome ;)

**Comment by jasonLaster** [comment] 2018-01-17 22:36
Hi @usmanibnesadiq thanks for the feedback. As a bit of context, we re-wrote the debugger over the past 2 years. The old version was written in Firefox XUL which was a superset of HTML and only available in the Firefox UI. The new version is re-written in react and redux, which can run as a local web page.

Unfortunately, the new UI is still buggy. We're working hard to go through the bug queue and are happy to prioritize the issues you're seeing.

We've fixed many of these issues over the past couple months, so i'd love to see what your experience is like with Firefox Nightly. https://www.mozilla.org/en-US/firefox/channel/desktop/

Also, we're all in slack and would be happy to debug with you: https://devtools-html-slack.herokuapp.com/

**Comment by usmanibnesadiq** [comment] 2018-01-17 23:09
Hi Jason, thanks for getting back. I am on latest nightly already and experiencing of all that. I am on your slack channel  and can share/show my experience. Thanks,

**Comment by jasonLaster** [comment] 2018-01-17 23:28
Cool. Happy to talk tomorrow. What's your slack handle?

**Comment by darkwing** [comment] 2018-02-05 23:38
Hello @usmanibnesadiq -- just wondering if you could provide a sample Angular URL where the performance is poor.  It would be super helpful!  Thank you!

**Comment by usmanibnesadiq** [comment] 2018-02-06 00:30
Hello Darkwing, Please clone this repo [https://github.com/usmanibnesadiq/angularcli] and do the following to reproduce the issues I reported.

1- Install Node (version 6.9+)
2- Install yarn
3- Open the cloned project using your fav editor and do "Yarn Install" at the root of project. Once all node modules are installed, do a "yarn start"
4- open your browser at http://localhost:4200/ Once you see the page, open your dev tools and press the "Check Debugger" button.
5- The tools will show you that debugger is stopped but wont load the source map. It will take lots of time to show this up. 
6- Once the debugger is hit in dev tools, try inspecting the values of "this" and "event" objects without doing anything. Nothing will load.

There is just one "OnClick" event attached to this button - you can modify this function and experiment to see your experience with Firefox (57, 58) dev tools. Please see my first post to cross check the issues.

This is the component where the click event is written. https://github.com/usmanibnesadiq/angularcli/blob/master/src/app/app.component.ts

The latest nightly (60.0a1 (2018-02-05) (64-bit) is picking up the debugger way better than stable 57/58 versions.

Thanks,
Usman

**Comment by digitarald** [comment] 2018-03-09 18:57
@usmanibnesadiq do you see the same issues on https://angular-quickstart.glitch.me/ , as minimal angular setup?

**Comment by usmanibnesadiq** [comment] 2018-03-11 08:42
mine is related to:

1- the time it takes to switch to debugger tab and hit your break point (nothing gets loaded for almost 30 seconds)
2- Once the debugger is hit, the variable evaluation is not there at all. The tooltips take ages to show any values in the objects.

Why cant we make it as fast as Chorme :) not only it loads the map files super fast but also shows all values instantly and inline. 

I have detailed the steps already - its a matter of 5 minutes to replicate this on any machine. This issue keeps me going back to chrome. Hoping for a competitive debugger in FF

**Comment by alessandrod** [comment] 2018-12-23 07:47
The "having to wait 30s" issue is likely fixed by https://github.com/devtools-html/debugger.html/pull/7302. 

The only issue I can still reproduce among those mentioned is that the watch expressions results don't keep their collapsed/expanded state.

**Comment by darkwing** [comment] 2019-01-29 23:22
Since the watch expression issue is much different than the original issue, I'm closing.  Thank you @alessandrod !

**Closed by darkwing** 2019-01-29 23:22 UTC
Labels: performance
