### ISSUE TITLE
[Frames] Actual error messages are hidden at the bottom of the call stack, when devtools docked to bottom of screen

### ISSUE THREAD

**Issue by sole** [devtools-html/debugger.html#4724] opened 2017-11-17 16:56 UTC
Using pause on exceptions, I am finding it extremely difficult to diagnose what the issue is with my code when it just STOPS and doesn't tell me what is wrong.

I realised after a while that if I scroll down I get an actual error. But why is it at the bottom? Surely we want the error to be super visible, not below the fold. See image for details:

![screenflow](https://user-images.githubusercontent.com/5609/32959005-1875f870-cbb8-11e7-8769-466a97f6fe22.gif)

I reckon people with bigger monitors and using the tools in a detached mode, or launching the debugger with launchpad, will not get these issues, but my situation is pretty common.

**Comment by wldcordeiro** [comment] 2017-12-28 07:11
@sole This is a super nice find! I totally agree that the errors should be surfaced higher.

**Comment by jasonLaster** [comment] 2018-01-04 17:44
Perhaps we move the message for errors to the top of the stack...

the first frame is the context of the exception...

**Comment by jasonLaster** [comment] 2018-01-25 02:02
Closing this issue and moving to the [enhancements](http://github.com/devtools-html/debugger.html/projects/5) board. 

* We will hopefully be able to prioritize it in the near future. 
* The issue is closed temporarily, but feel free to continue discussing the issue

**Closed by jasonLaster** 2018-01-25 02:02 UTC
Labels: enhancement, not-available
