### ISSUE TITLE
Debugger crashes on sparse local storage

### ISSUE THREAD

**Issue by bjorn3** [devtools-html/debugger.html#1375] opened 2016-12-04 10:41 UTC
When I tried debugging some javascript with firefox developer edition debugger.html constantly crashed at the same point in my code. I got a popup saying debugger.html was running too long. If I tried to use the browser I couldn't use the menu button or any other button of for example noscript. When I finally tried to close firefox I got display error in the browser window and had to kill it.
Screencast: [https://vid.me/tT3K](https://vid.me/tT3K)

Firefox version: 52.0a2 aurora
e10s: activated

**Comment by bjorn3** [comment] 2016-12-04 10:47
I guess its because debugger.html can't handle sparse arrays.

```javascript
> console.log(lists)
Object [ <1 empty slot>, "{"id":1,"title":"Test","list_collec…", "{"id":2,"title":"Salzgitter Heute",…", <7 empty slots>, 66261271 more… ]
```

**Comment by jasonLaster** [comment] 2016-12-04 20:55
Uhoh. We'll definitely look into that. 

Hmm. Could you try creating a test case?

Also is it possible for me to go to your page?

**Comment by bjorn3** [comment] 2016-12-05 18:34
Minimal reproduction:
```javascript
localStorage[1] = "a test";
localStorage[2] = "a";
localStorage[66261280] = "another test";
let data = JSON.parse(JSON.stringify(localStorage));
console.log(data) // Put breakpoint here
```
Needs two low numbers and then a high number.

**Comment by jasonLaster** [comment] 2016-12-05 18:48
Thanks.

At first I thought you used your phone number as the key.

I'll look into it later today.

**Comment by bjorn3** [comment] 2016-12-05 18:50
Its a database key.

**Comment by jasonLaster** [comment] 2016-12-05 19:00
Makes more sense

**Comment by bjorn3** [comment] 2016-12-05 20:00
Screencast debugging debugger.html while debugging the snippet above: https://vid.me/OoQd.

Note: mouse position seems to be off quite a bit.

**Comment by clarkbw** [comment] 2016-12-09 01:42
When I tried to hunt this down it looked like it broke here: https://github.com/devtools-html/debugger.html/blob/master/src/reducers/pause.js#L45 the `fromJS(pauseInfo)` call was spinning. Not sure if other people are seeing that as well.

**Comment by jasonLaster** [comment] 2016-12-09 01:44
Thanks. That looks correct.

I'll try that

**Comment by jasonLaster** [comment] 2016-12-09 01:54
@clarkbw @bjorn3 just added a test case here https://github.com/devtools-html/debugger.html/pull/1407. Is this right? I'm not seeing it on a mac...

**Comment by clarkbw** [comment] 2017-01-22 07:37
I still believe this has to do with ImmutableJS and the `fromJS` method.

But I'm not able to reproduce this with the debugger anymore.  I am seeing it still on DeveloperEdition and in Nightly but not with the current master on GitHub.

**Comment by clarkbw** [comment] 2017-01-23 23:55
Lets check again after the next bundle lands.  Likely an issue with reps.

**Comment by yurydelendik** [comment] 2017-02-02 22:42
Smaller test case by using only ImmutableJS

```
var ar = [1,2];
ar[66261280] = 3;
var seq = Immutable.Seq(ar);
seq.forEach(i => {});
```

**Comment by yurydelendik** [comment] 2017-02-02 23:36
So we create grip (see e.g. https://dxr.mozilla.org/mozilla-central/source/devtools/server/actors/object.js#1224) that will have the following structure:

```
{
  ...
  "preview": {
    "items": {...},
    "kind": "ArrayLike",
    "length": 66261281
}
```

Which will be feed to the `fromJSON` and immutable-js (with help of https://github.com/facebook/immutable-js/blob/master/src/utils/isArrayLike.js) will decide that it is an Array and will use ArraySeq producing the same iloop as shown above.

**Comment by clarkbw** [comment] 2017-02-03 00:09
Should we just do some transform on sparse arrays? `Object.keys(ar).map(k => ar[k])`

**Comment by yurydelendik** [comment] 2017-02-03 00:12
> Should we just do some transform on sparse arrays? Object.keys(ar).map(k => ar[k])

It's not really an array. It's just an object with numeric `length` property. The items of array does not matter in this case, it's just ArraySeq running loop for 66261281 undefined's.

**Comment by yurydelendik** [comment] 2017-02-03 01:03
The hack bellow somewhat fixes the loop problem.

```diff
@@ -41,6 +41,10 @@ function fromJS(value: any) : any {
     return value;
   }
 
+  if (typeof value.length === "number") {
+    value.length = "" + value.length;
+  }
+
   // Otherwise, treat it like an object. We can't reliably detect if
   // it's a plain object because we might be objects from other JS
   // contexts so `Object !== Object`.
```

**Comment by jasonLaster** [comment] 2017-02-10 15:55
@juliandescottes and I are looking into this:

We're going to try to do two things:
1) not hydrate immutable objects
2) bucket our properties - here's a branch for the [bucketing]( https://github.com/jasonLaster/debugger.html/tree/large)

**Comment by jasonLaster** [comment] 2017-02-14 18:19
This is fixed by not hydrating null items in a sparse array. We will also want to add bucketing so that we don't render all of the keys in large objects, but we can handle that in another issue

**Comment by clarkbw** [comment] 2017-02-16 17:38
Looks like this issue is fixed.

**Closed by clarkbw** 2017-02-16 17:38 UTC
Labels: bug, bug: P1, Release: Commitment
