### ISSUE TITLE
[Editor] Improve EmptyLines

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#3833] opened 2017-08-31 00:43 UTC
A few ways I think my EmptyLines logic could be improved:

- [ ] The debugger has breakpoint setting logic whereby if you try to set a debugger at a certain point, the breakpoint is moved to a different line:

```js
var TodoRouter = Backbone.Router.extend({
	routes: {
		'*filter': 'setFilter'
	}, // Trying to add breakpoint here moves breakpoint to `setFilter` line

	setFilter: function (param) {
		// ....

```

- [ ] If the only contents of the line are `"use strict";`, we can empty that line.  Consequently, the previous point triggers on this line too.

**Comment by darkwing** [comment] 2017-08-31 01:46
Tracing through the source, the breakpoint location shifting is occurring in:

*  src/reducers/breakpoints.js
  -> `addBreakpoint`
  ->  `if(previousLocation)`

**Comment by jasonLaster** [comment] 2017-08-31 13:33
Hmm, this makes me think that we might want to make empty lines a little bit more generous. Basically make it impossible to add a bp on the end of the object curly. Also, it'd be nice to exclude the route keys because there's nothing called. It'd be nice to have some smarter algorithms.

**Comment by jasonLaster** [comment] 2017-08-31 13:33
We can also let this sit for a bit and revisit it in a month or two...

**Comment by darkwing** [comment] 2017-09-01 20:22
Empty lines is also not as precise in HTML files:

<img width="883" alt="htmllines" src="https://user-images.githubusercontent.com/46655/29986514-60ba537c-8f29-11e7-9616-86fc76cc985a.png">

**Comment by jasonLaster** [comment] 2017-10-27 20:37
closing as a dupe of #4047. I also think that the HTML has been fixed. If not, lets open it in a separate PR

**Closed by jasonLaster** 2017-10-27 20:37 UTC
Labels: enhancement
