### ISSUE TITLE
[PrettyPrint] pauses without a bp on load

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/debugger.html#5519] opened 2018-02-23 21:44 UTC
1. Load https://www.microsoft.com/en-us/software-download/windows10
2. Open debugger
3. Use Ctrl+P to find sources, search `script.jsx?k=05`, there should only be one result
4. Pretty print
5. Search `n.redirection.redirect = function () {`
6. Add a breakpoint inside that function, e.g. line 4510
7. Reload the page

Result: the debugger pauses at line 5071, the breakpoint list says "No breakpoints" despite "Paused on a breakpoint".

Expected: the debugger pauses at line 4510, the breakpoint list contains that breakpoint.

![screencast](https://user-images.githubusercontent.com/7477678/36618348-22c0a052-18eb-11e8-945b-9af490f85a2b.gif)

**Comment by munyari** [comment] 2018-02-24 21:55
Attempting to reproduce, but my breakpoints are not persistent across page refreshes

**Comment by jasonLaster** [comment] 2018-02-27 14:38
Hmm, I'll look into this next week after we address some other pretty print / breakpoint bugs

**Comment by jasonLaster** [comment] 2018-05-18 17:38
Hey @ATCraiger sorry for missing this

**Comment by jasonLaster** [comment] 2018-05-23 15:09
@ATCraiger can you try reproing again on nightly?

**Comment by jasonLaster** [comment] 2018-05-23 15:16
So, i just tried and found that I could pause, but it looks that pretty print is not mapping to the "right" spot because we pause at a different location than where the breakpoint is set:

![](http://g.recordit.co/p4WkReNQTV.gif)

I'm going to reclasify as a pretty print bug until we can confirm

**Comment by Loirooriol** [comment] 2018-05-23 15:27
I still don't see the breakpoint in the breakpoints list.

**Comment by jasonLaster** [comment] 2018-05-23 20:12
![](http://g.recordit.co/WVYAQZ4zGf.gif)

**Comment by darkwing** [comment] 2018-06-07 17:56
This may have been fixed by: https://github.com/devtools-html/debugger.html/pull/6486

**Comment by darkwing** [comment] 2018-09-04 17:16
This has been fixed -- breakpoint now displays in sidebar and pauses at correct time.

**Comment by Loirooriol** [comment] 2018-09-04 19:50
The call stack is still wrong, though.

**Comment by jasonLaster** [comment] 2018-10-29 21:16
1. sometimes we're scrolled to line  1
2. resume will pause again
3. the call stack is off

**Comment by loganfsmyth** [comment] 2018-10-31 16:29
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1503436 with a patch for the issue of pausing at the wrong location.

I'll take a peak now to see what is causing the scroll jumping.

**Comment by jasonLaster** [comment] 2018-11-21 14:10
Yes.

We can file a separate issue for the scrolling issue

**Closed by jasonLaster** 2018-11-21 14:10 UTC
Labels: backlog, bug

**Comment by jasonLaster** [comment] 2018-11-21 14:22
i can't reproduce the scrolling issue either!
