### ISSUE TITLE
Return values of functions are not displayed

### ISSUE THREAD

**Issue by Standard8** [devtools-html/debugger.html#3813] opened 2017-08-29 19:28 UTC
STR:

1) Step through a function using the Step Into option.
2) Get to a stage where the function jumps to the end and is ready to return
3) Try and work out what value the function is returning.

Actual Results

=> No indication (that I can see) of the value

Expected Results

=> Indication of what the function returns.

iirc the old xul based debugger used to do this.

I'm using today's FF nightly and the browser toolbox.

**Comment by jasonLaster** [comment] 2017-08-30 02:14
This is a likely a duplicate of #3390. I believe @codehag and @tromey are looking at this case tomorrow.

**Closed** 2017-08-30 02:14 UTC
