### ISSUE TITLE
Add breakpoint in closed source tab accidentally

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#1984] opened 2017-02-10 06:29 UTC
**Steps to reproduce**
1. Go to "about:home"
2. Select source "chrome://browser/content/contentSearchUI.js"
3. Click Pretty Print button -> formatted source tab "{ } contentSearchUI.js" will be opened.
4. Close formatted source tab "{ } contentSearchUI.js"
5. Add breakpoint on line 7 in "contentSearchUI.js" tab
6. breakpoint is added in "contentSearchUI.js:formatted: 6"

**Actual Results**
breakpoint is added in closed tab "contentSearchUI.js:formatted: 6"

**Expected Results**
Add breakpoint in active source tab.

![add-breakpoint-in-closed-source-tab](https://cloud.githubusercontent.com/assets/13914314/22816364/f58733e6-efa4-11e6-9183-797764ac3329.gif)

**Comment by clarkbw** [comment] 2017-02-10 18:22
I'm able to reproduce this in Nightly.  Now we just need to be able to reproduce it in development mode.

**Comment by jasonLaster** [comment] 2017-02-10 22:10
Thanks for filing the bug. This is actually intended behavior because we will store breakpoints in the original location (a.k.a pretty location).

* We can do something nice here and jump you to the original location where we store the breakpoint if it would help.

**Comment by clarkbw** [comment] 2017-02-10 22:17
> I'm able to reproduce this in Nightly. Now we just need to be able to reproduce it in development mode.

Oh, I was actually looking at the wrong bug.  I thought this was #1982

**Comment by rrandom** [comment] 2017-02-11 04:14
Should the the tab auto switch to the prettied tab `{ } contentSearchUI.js` when add breakpoint on `contentSearchUI.js`?

**Comment by magicp-github** [comment] 2017-02-11 09:03
It is complicated behavior for me. Because in step 4, if click on line 1, new breakpoint will be added in original tab. I think that If it is intended behavior, both of original and prettied tab should not be displayed at the same time.

**Comment by clarkbw** [comment] 2017-05-04 22:16
I think #2813 is related here.  Going to close this one out for now as I don't think we're getting to it right away.  I can only reproduce it on `about:` pages and not with other websites, that would be good to get a better test case.

**Closed by clarkbw** 2017-05-04 22:16 UTC
Labels: bug, low-priority
