### ISSUE TITLE
DOM objects do not offer useful properties when expanded

### ISSUE THREAD

**Issue by gijsk** [devtools-html/debugger.html#3035] opened 2017-05-30 13:52 UTC
Useful: things like the text content, id, classes, checked state, src property, any attributes - anything specific to the node.
Not useful: prototype methods.

Somehow, when using a watch or local variable entry, only their `__proto__` shows up, and I can't look at useful things (like, say, an event's target, or the src property of an iframe, or the id of another DOM node, ...).

**Comment by jasonLaster** [comment] 2017-05-30 13:54
Thanks @gijsk this is a dupe of #2849 which we'll fix soon. It's the biggest issue with the new debugger UI at the moment :)

**Closed by jasonLaster** 2017-05-30 13:54 UTC
