### ISSUE TITLE
web2pdfextension.17@acrobat.adobe.com (Acrobat Pro Plugin) breaks debugger

### ISSUE THREAD

**Issue by MikeRatcliffe** [devtools-html/debugger.html#4813] opened 2017-11-28 11:26 UTC
The user that reported this was using Firefox 57.0 (64 bit) in German on Win10 but the language probably doesn't matter.

#### STR

1. Install Acrobat Pro `on` a Windows 10 box.
2. Go to https://www.soscisurvey.de/example/?q=fail&password=demo&debug7
3. Open the developer tools, and reload the page.

Neither the DevTools will work any more, nor the sliders, nor the F5 button.

#### Screenshot

![acrobatbreaksdebugger](https://user-images.githubusercontent.com/116941/33317279-88cd47da-d42e-11e7-94ac-5e9ad3a08257.png)

**Comment by codehag** [comment] 2017-11-28 11:29
Thanks for the bug report, we will take a look into it!

**Comment by zaggy** [comment] 2017-11-28 11:42
Just checked on my machine. I have latest Adobe Acrobat DC installed on Windows 10 machine. Don't have the described behavior and can't reproduce the issue 
![image](https://user-images.githubusercontent.com/69977/33318075-70d03098-d48d-11e7-961d-c9eb2cae578c.png)

**Comment by zaggy** [comment] 2017-11-28 11:44
Maybe the issue is in German version? I'll spin a virtual machine with German Windows 10 later this week.

**Comment by codehag** [comment] 2017-11-28 11:45
thanks for taking a look @zaggy. Yeah it would be great if you can try the german vm. I will run it as well tomorrow on a windows machine. @MikeRatcliffe, is there more information from the user? are they available for questions anywhere?

**Comment by MikeRatcliffe** [comment] 2017-11-28 12:12
You can contact him over Mozilla discourse via the Message button:
https://discourse.mozilla.org/u/dominik/activity/replies

**Comment by MikeRatcliffe** [comment] 2017-11-28 12:14
I suspect we will need to find out which acrobat version he is using to reproduce this.

**Comment by juliandescottes** [comment] 2017-11-28 13:25
I posted in discourse, but I'll dupe here. I think this is an issue with break on all exceptions + webextensions.

It seems like @Dominik currently has its debugger set to “Pause on all exceptions” (according to the color of the associated icon on the screenshot below)

![image](https://user-images.githubusercontent.com/1141550/33321972-dcddc0ac-d447-11e7-92e1-c36866f2a4d2.png)

The mentioned extension happens to throw an exception on the load of the page. You could click again on this icon to no longer break on exceptions. So the enhancement here would be to avoid breaking on webextensions code maybe?

**Comment by jasonLaster** [comment] 2018-01-25 01:44
I just tried again and it worked alright in FF60.

**Comment by jasonLaster** [comment] 2018-03-14 20:55
closing as we have made a lot of improvements to pausing on exceptions in the past couple of months.

**Closed by jasonLaster** 2018-03-14 20:55 UTC
Labels: bug, not-available
