### ISSUE TITLE
[Perf] Jank caused by debugger open in the background

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#5087] opened 2018-01-11 21:37 UTC
Related to #4896, but looks like different bottlenecks in the profile.

STR:

- Set a breakpoints on http://firefox-dev.tools/debugger-examples/examples/wasm/fib/fib.index.html and hit refresh to hit the breakpoint and pause
- Open Wikipedia in a new tab (keep debugger open in background) and scroll down

AR: 150ms+ hangs during scrolling

https://perfht.ml/2CScodv

- Profile renders a ton of react after receiving new data; which doesn't make sense as it it in the background and should do unnecessary work

**Comment by jasonLaster** [comment] 2018-01-11 21:45
Nice find!

Did you just take this?

**Comment by digitarald** [comment] 2018-01-11 23:36
> Did you just take this?

Yes, Nightly 59.0a1 (2018-01-10) (64-bit).

**Comment by jasonLaster** [comment] 2018-01-14 21:06
@digitarald could you add a more specific STR?

**Comment by digitarald** [comment] 2018-01-14 23:12
@jasonLaster ok, done.

**Comment by jasonLaster** [comment] 2018-03-14 21:30
closing as a dupe of #4896

**Closed by jasonLaster** 2018-03-14 21:30 UTC
Labels: performance
