### ISSUE TITLE
[Sources] Show “Loading sources” label

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/debugger.html#4863] opened 2017-12-06 14:37 UTC
Steps to reproduce:
1. Go to https://debugger-html-css-grid.glitch.me/
2. Open the debugger 
3. Reload

Expected results:
The source panel shows a "Loading sources" label
Actual results:
The sources panel shows "this page has no sources" label, and then is updated

![dec-06-2017 15-41-40](https://user-images.githubusercontent.com/578107/33667077-1cec1202-da9c-11e7-8a44-38f84ecf0961.gif)

In the gif case, it is a bit confusing, but fine. But in some cases you have a flicker of the sources panel because it quickly switches from "no sources" to the tree.

Having a "loading sources" which is displayed a decent amount of time so we don't have the flicker would be nice.

----

I don't know how feasible this is since sources can be added at anytime, but I guess we might have some initial source fetching we can rely on to handle this.

**Comment by jasonLaster** [comment] 2018-01-17 19:32
Closing this issue and moving to the [enhancements](http://github.com/devtools-html/debugger.html/projects/5) board. 

* We will hopefully be able to prioritize it in the near future. 
* The issue is closed temporarily, but feel free to continue discussing the issue

**Closed by jasonLaster** 2018-01-17 19:32 UTC
Labels: enhancement, not-available
