### ISSUE TITLE
Links pretty-printed sources from Console don't do to the right line

### ISSUE THREAD

**Issue by digitarald** [devtools-html/debugger.html#4834] opened 2017-11-30 23:38 UTC
Follow up from https://bugzilla.mozilla.org/show_bug.cgi?id=952127 , that fixed prettyfied source links in Console.

STR:

- Open application.js on Slack
- Prettyprint. Get coffee, this can take a while
- Open Console and click one of the many logs with labels like `
application.c581a1e141626b88f1bc.min.js:formatted:25305`

AR:
- Pretty printed file is opened but line isn't scrolled into view or highlighted

ER:
- Open pretty printed file with the right line

**Comment by jasonLaster** [comment] 2017-11-30 23:42
This is a dupe. CC @lukaszsobek @darkwing

**Comment by lukaszsobek** [comment] 2017-12-05 09:59
Dupe of #3778

**Closed by lukaszsobek** 2017-12-05 09:59 UTC
Labels: bug, not-available
