### ISSUE TITLE
Sidebar resizing performance

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/debugger.html#676] opened 2016-09-07 08:28 UTC
I'm noticing a really low framerate when moving the splitters around. Especially when moving the left one (where the source tree is displayed).
If I do the same thing on the current debugger in Firefox, or in Chromedevtools, it's really smooth, the splitter just follows the mouse as you'd expect.
With the new debugger however, the splitter lags behind and the UI only refreshes at intervals, which gives the impression that the new debugger is slower than the old one.

![resize](https://cloud.githubusercontent.com/assets/1152698/18304878/2f8eb360-74e5-11e6-89cc-2c75411bf904.gif)

I hope this gif captures it, you should be able to see, especially the first time I make the sidebar bigger, that there are a few really noticeable jumps in the resizing.

There might be forced reflows in the JS code that resizes the sidebar.

**Comment by jasonLaster** [comment] 2016-09-07 13:02
Nice find. Lets investigate quickly to see if the fix is likely in the splitter component or how we're using it.

**Comment by jlongster** [comment] 2016-09-07 13:22
We're going to bring in Honze's revamped SplitBox which has received more love so we should just focus on that component. It's fine if it's like this for next week or two.

**Comment by jlongster** [comment] 2016-09-07 16:06
Just tested this and the ride sidebar resizes fine, it's only the left sidebar. I'm guessing that there's an extraneous render and it might even be the editor, which would definitely be slow. Should be pretty easy to fix.

**Comment by wldcordeiro** [comment] 2016-09-30 17:11
The last time this was tested was prior to Honza's SplitBox being brought in, let's reevaluate now that it's in?

**Comment by clarkbw** [comment] 2016-11-11 16:07
I'm not able to reproduce this anymore

**Comment by jasonLaster** [comment] 2016-11-15 18:50
closing, we can open it again if we see it.

**Closed by jasonLaster** 2016-11-15 18:50 UTC
Labels: enhancement
