### ISSUE TITLE
[Breakpoint] Conditional breakpoint UI can be opened more than once (and can't be closed afterwards)

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#4964] opened 2017-12-21 17:22 UTC
STRs:

- Go to http://firefox-dev.tools/debugger-examples/examples/todomvc/
- open Debugger
- open any source (e.g. app-view,js)
- right click on the gutter to add a conditional breakpoint on line 11
- right click on the gutter to add a conditional breakpoint on line 21
- right click on the gutter to add a conditional breakpoint on line 30
- click in the UI that was opened in the previous step
=> This last UI is closed

After that, all the remaining inputs for conditional breakpoints are broken. They can't be validated or closed.

![conditional_bp_bug](https://user-images.githubusercontent.com/1141550/34267080-d50bec28-e67b-11e7-8377-8f17ae66402e.gif)

**Comment by lukaszsobek** [comment] 2017-12-23 19:26
What's the expected behavior in this case?

**Comment by nyrosmith** [comment] 2018-01-04 17:29
I can reproduce it only in the panel. In launchpad it works as expected.
Not sure what's going wrong there...

**Comment by jasonLaster** [comment] 2018-01-04 17:38
Lets see if we can investigate a bit before we mark it available...

**Comment by nyrosmith** [comment] 2018-01-06 08:13
Why shouldn't this work in the panel too? https://github.com/devtools-html/debugger.html/blob/f9149b7d312f902a532c235d1e5bc90a2dca30ca/src/components/Editor/ConditionalPanel.js#L150

**Comment by jasonLaster** [comment] 2018-02-15 15:44
this should be fixed because of the onblur

**Closed** 2018-02-26 23:24 UTC
Labels: bug, not-actionable
