### ISSUE TITLE
Scopes pane shows null when values may be uninitialized

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#3700] opened 2017-08-17 20:41 UTC
Coming from [bug 1362451](https://bugzilla.mozilla.org/show_bug.cgi?id=1362451) you'll see the example shows variables in the old debugger start as `undefined` and then take the value `uninitialized`.

**Comment by codehag** [comment] 2017-08-21 16:11
copy-paste from the issue:

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0
Build ID: 20170418123106

Steps to reproduce:

1. Open attached example.html in Firefox 53.0 or Firefox Developer Edition 54.0a2 (both affected, new and old debugger).
2. Open Developer Tools, go to Debugger.
3. Set breakpoint in line 8 (first statement in block).
4. Look at debugger Variables/Scopes view.
5. Click "step over".
6. Look at debugger Variables/Scopes view again.


Actual results:

- At step 4: letBlock/constBlock variables (bound via let/const) are shown as undefined in debugger (in Firefox 53.0 or Firefox Developer Edition 54.0a2)
- At step 6, in Firefox 53.0 (old debugger): letBlock/constBlock shown as "(uninitialized)"
- At step 6, in Firefox Developer Edition 54.0a2 (debugger.html): letBlock/constBlock shown as null


Expected results:

- Block scoped variables should not visibly change their value when an unrelated statement is executed. Should either stay at undefined or shown "(uninitialized)" all the time (until declaration statement is actually reaced).
- Firefox Developer Edition 54.0a2 / debugger.html behavior is especially confusing, since "null" indicates explicit intent by the programmer, unlike undefined which is more sensible.

**Comment by jasonLaster** [comment] 2018-03-07 21:43
closing as this will be managed in bugzilla

**Closed by jasonLaster** 2018-03-07 21:43 UTC
Labels: bug, server
