### ISSUE TITLE
[Pause] Debugger is getting the source line numbers/highlighting wrong

### ISSUE THREAD

**Issue by Standard8** [devtools-html/debugger.html#3371] opened 2017-07-19 09:37 UTC
STR:

1) Build Firefox from latest master in `--enable-artifact-builds` mode (I've not tested non-artifact).
2) Start up Firefox, visit a random webpage you haven't visited before.
3) Open up devtools, cmd-P and search for `browser-places.js`
4) Add a breakpoint in bookmarkPage
5) Click the star icon on the main UI to bookmark the page.

Expected Result
=> Debugger breaks and highlights the right source line and steps through correctly.

Actual Result
=> Debugger breaks, but source line numbers & highlights are wrong.

**Comment by Standard8** [comment] 2017-07-19 09:43
I just set a breakpoint earlier in the function than I had been doing, that seems to have somehow kicked the debugger back onto the right line numbers, such that now I can't reproduce.

**Comment by jasonLaster** [comment] 2017-07-20 15:17
Thanks for filing

**Comment by jasonLaster** [comment] 2017-07-20 22:36
This is what i'm currently seeing:

![](http://g.recordit.co/5rl94cKFi6.gif)

what do you mean by the line numbers are off:

1. the line number value is wrong
2. they're hidden and the breakpoint is hidden
3. the debugger does not jump to the correct location
4. some other weird behavior :)

**Comment by Standard8** [comment] 2017-07-21 06:38
When I see it, what I see is that the debugger breaks and highlights an incorrect line, e.g. breaking on line 403, it would then effectively be on line 402 (determined by looking at the variable values), and will then be a line behind constantly.

Additionally, the call stack has the wrong line number in, iirc.

I've also seen this type of behaviour with xml files, but that may be a slightly different issue.

**Comment by jasonLaster** [comment] 2017-07-21 13:31
Ahh, I wonder if this is a dupe of #3282? The server is off by one with XUL documents (affects the old ui too).

**Comment by jasonLaster** [comment] 2017-07-21 13:32
Ahh

**Comment by jasonLaster** [comment] 2018-03-07 21:50
This seems to be working now in nightly

![](http://g.recordit.co/Zt8o4MZzo5.gif)

We've done a lot of work here to stabilize breakpoints and stepping. Let me know if you can reproduce it.

**Closed by jasonLaster** 2018-03-07 21:50 UTC
Labels: bug, server

**Comment by kupietools** [comment] 2019-09-24 08:47
This has been consistent with me in every version of Firefox for, literally, the last two or three years. The debugger highlights the second line following the line it's actually executing. It's making debugging incredibly difficult to follow.

**Comment by jasonLaster** [comment] 2019-09-24 14:04
Could you please file the bug here - https://bugzilla.mozilla.org/enter_bug.cgi?product=DevTools&component=Debugger
