### ISSUE TITLE
Expanded variables are collapsed again after every step

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#6897] opened 2018-08-29 06:36 UTC
From https://github.com/devtools-html/devtools-core/issues/744 (where there is already some discussion)

This was reported on the debugger, what would be great is if we could maintain the state. any thoughts on how to do this?

From Bugzilla issue https://bugzilla.mozilla.org/show_bug.cgi?id=1405402

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
Build ID: 20170926190823

Steps to reproduce:

1. Set breakpoint, run into breakpoint
2. Find object variable, expand it
3. Make single step

Actual results:

Expanded variables are collapsed again

Expected results:

Expanded variables should stay expanded

**Comment by juliandescottes** [comment] 2018-08-29 06:38
cc @nchevobbe you had some WIP patches you mentioned in the initial issue, anything new since the issue was closed on devtools-core?

**Comment by nchevobbe** [comment] 2018-08-29 07:31
I don't think so. The thing I started working on ended up being complex and we agreed it wasn't a big deal for a given case in the debugger, but I don't think it was this case, which is pretty important.

**Comment by jasonLaster** [comment] 2018-08-29 12:39
I think this is a dupe of #3269 which we plan on doing in 64 #6777

**Comment by Standard8** [comment] 2018-08-29 12:51
Looks like it, I even commented on that one.... (though someone else will need to close this).

**Closed** 2018-08-29 12:59 UTC
Labels: not-available
