### ISSUE TITLE
[Breakpoints] After setting a breakpoint, debugger refuses to step through the code

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#5807] opened 2018-03-28 06:07 UTC
To reproduce

0. With Firefox Desktop Responsive Design mode. (window 360px/640px, Firefox Android UA, touch activated). 61.0a1 (2018-03-27) (64-bit)
1. Go to http://siberiastationspa.com/infos-pratiques/
2. Open the debugger
3. Find `function initHashClick()` in `default.min.js`
4. Set a breakpoint at the beginning of the code in initHashClick(). See screenshot
5. Go back to the viewport window.
6. click on the 3 stripes menu
7. click on of the menu item.

<img width="1007" alt="capture d ecran 2018-03-28 a 15 02 31" src="https://user-images.githubusercontent.com/505230/38011789-c2a240f4-3299-11e8-811f-cffa8b68aed1.png">

Expected:
The code stops and shows the line where we put the breakpoint.

Actual:
The debugger stops the execution as wanted, but doesn't show any line of codes where it stopped and the steps in/out/over etc are not effective at all.

The only way to go out of this state is to close the devtools window and reopen it.

Always reproducible.

**Comment by jasonLaster** [comment] 2018-03-28 12:31
Thanks @karlcow I'll look into it!

**Comment by darkwing** [comment] 2018-09-04 17:10
I can no longer reproduce this.  Closing due to @jasonLaster 's comment as it's likely fixed..

**Closed by darkwing** 2018-09-04 17:10 UTC
Labels: bug
