### ISSUE TITLE
Jest memory leak (maxListeners)

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4894] opened 2017-12-08 19:46 UTC
I'm seeing an intermittent on CI and locally w/ a memory leak. I'm pretty sure it is in our actions... 

> (node:16088) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit

https://circleci.com/gh/devtools-html/debugger.html/9020

**Comment by jasonLaster** [comment] 2017-12-09 15:47
Yeah... That's true. It would be nice to find when it was introduced... 

I think we need a `git bisect`

The nice thing is it's easy to see it locally.

**Comment by jasonLaster** [comment] 2017-12-09 18:15
so - it looks like it might have started Nov 3rd, but it is not the cause of the intermittent

**Comment by lukaszsobek** [comment] 2017-12-09 19:16
The memory leak might have been there earlier, but because we did not hit the threshold we did not notice it was there.

**Comment by ryanjduffy** [comment] 2017-12-11 21:09
I don't think this is a testware issue within the debugger. `EventEmitter` isn't (afaik!) used for managing events in the React stack. Instead, I'm curious if `jest` is starting too many workers to execute tests. In searching source, I noticed that `mocha-runner` comes up several times as listening to `unhandledRejection`. Not sure if that's the cause but could be worth a test to limit the worker pool.

https://facebook.github.io/jest/docs/en/cli.html#maxworkers-num

**Comment by lukaszsobek** [comment] 2017-12-19 21:42
Fix merged, closing issue.

**Closed by lukaszsobek** 2017-12-19 21:42 UTC
Labels: testing
