### ISSUE TITLE
Search is slow (hangs/stalls browser) on big files

### ISSUE THREAD

**Issue by jnachtigall** [devtools-html/debugger.html#3709] opened 2017-08-18 11:09 UTC
Use case:

I had a vendors.min.js which is a concatenated, big file (1.5 MB or so) and needed to see if a certain lib is in there. Searching in this file for a specific strings makes Firefox Nightly hang (not responding). I guess it should be easily reproducable by just loading a huge file.

I can send a perf profile if this helps, e.g. using the https://perf-html.io/ addon or the browser performance devtools tool, whichever would be better.

FWIW, I am using the Debugger.html version of Firefox Nightly

**Comment by jasonLaster** [comment] 2017-08-18 12:47
send a perf-html report!

**Comment by jnachtigall** [comment] 2017-08-18 13:21
Here you go: https://perfht.ml/2uXsTRK

Here's a screenshot. I hit the search once => FF freezes, hit it again after search return after 10s or so => freezes again for 10s or so (I know it's not cheap to search like this, but I guess it should still not freeze you're browser, also it works fine in Chrome):
![spinning-devtools](https://user-images.githubusercontent.com/3307404/29460377-12c87240-8428-11e7-9087-7b6bdb256ac6.gif)

I guess this is just JS being to slow for such searches (though I wonder why it works in Chrome then). I wished FF could use something like rip-grep like VSCode does nowadays (whose search across files is extremely fast) https://code.visualstudio.com/updates/v1_11#_text-search-improvements Though I guess you cannot call binaries from JS

**Comment by jasonLaster** [comment] 2017-09-08 17:29
i'm closing because I believe this is a dupe of #3460.

Nightly should have the fix on monday, which will be a good time to test.

**Closed by jasonLaster** 2017-09-08 17:29 UTC
Labels: performance
