### ISSUE TITLE
[Breakoints] Remote Debugging Firefox Session Active Breakpoint is not getting highlighted

### ISSUE THREAD

**Issue by Anzumana** [devtools-html/debugger.html#4167] opened 2017-09-26 09:28 UTC
Sample Project that were the issue is occurring:
```bash
git clone https://github.com/Anzumana/overwatch
cd overwatch
npm install
npm start
```

![screen shot 2017-09-26 at 11 14 00](https://user-images.githubusercontent.com/2629041/30852997-bd65fb66-a2ad-11e7-9cff-6b6fb3f04bf8.png)

I am running the debugger in chrome based on the master branch ( yarn start )

The behaviour i am seeing is that i don't know what part of the code the debugger has stopped on. As it is not being highlighted.
I would like to use master for debugging and to make some videos showing of some new features.
But for that the interaction i have between running the debugger with yarn start and and browser instance has to work properly.

**Comment by nyrosmith** [comment] 2017-09-26 09:44
Not at my machine right now. @Anzumana  does switching to the light theme make a difference?

**Comment by Anzumana** [comment] 2017-09-26 13:48
sec let me check

**Comment by Anzumana** [comment] 2017-09-26 13:52
![screen shot 2017-09-26 at 11 14 00](https://user-images.githubusercontent.com/2629041/30863997-b6250de0-a2d2-11e7-99bb-05c0c1313568.png)
sadly same behavior.

**Comment by nyrosmith** [comment] 2017-09-26 13:55
@Anzumana thx for checking. I'll try to find the cause

**Comment by nyrosmith** [comment] 2017-09-27 04:13
Hi @Anzumana I just checked on my machine and it works. If you look at your screenshots in the "Scopes" panel the debugger tells you that it hasn't paused.
It looks to me you navigated to your demo repo before you attached/started the debugger. So your app already started and the code you set your breakpoints already ran.
Switch to the debuggee and refresh the page and everything should be fine.

I'm closing this for now but feel free to reopen if this doesn't solve your issue

**Comment by Anzumana** [comment] 2017-09-28 08:20
in both screenshots the ui shows that its actually paused.  I did what you suggested before many time before posting the issue. So that does not help sadly.

**Comment by Anzumana** [comment] 2017-09-28 08:29
this is a screen of what it should look like from firefox developer edition with the build in debugger.

![screen shot 2017-09-28 at 10 25 31](https://user-images.githubusercontent.com/2629041/30956450-aad9f106-a437-11e7-9071-5f2fd5fa468f.png)

**Comment by nyrosmith** [comment] 2017-09-28 08:56
I reopen this until we know what's exactly happening.
@Anzumana and I will do a remote session to tackle this down

**Comment by Anzumana** [comment] 2017-09-28 16:22
<img width="903" alt="screen shot 2017-09-28 at 18 21 13" src="https://user-images.githubusercontent.com/2629041/30978114-eb669e62-a479-11e7-96f5-9580ba5882b5.png">
```
Uncaught (in promise) TypeError: Cannot read property 'url' of undefined
    at listeners.map.l (debugger.js:92062)
    at Array.map (<anonymous>)
    at formatListeners (debugger.js:92058)
    at asPaused.then.listeners (debugger.js:92050)
    at <anonymous>
debugger.js:92034 Uncaught ReferenceError: services is not defined
    at setTimeout (debugger.js:92034)
debugger.js:110726 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at Scopes.getRoots (debugger.js:110726)
    at Scopes.render (debugger.js:110753)
    at debugger.js:75460
    at measureLifeCyclePerf (debugger.js:74741)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (debugger.js:75459)
    at ReactCompositeComponentWrapper._renderValidatedComponent (debugger.js:75486)
    at ReactCompositeComponentWrapper._updateRenderedComponent (debugger.js:75410)
    at ReactCompositeComponentWrapper._performComponentUpdate (debugger.js:75388)
    at ReactCompositeComponentWrapper.updateComponent (debugger.js:75309)
    at ReactCompositeComponentWrapper.receiveComponent (debugger.js:75211)
debugger.js:110726 Uncaught TypeError: Cannot read property 'map' of undefined
    at Scopes.getRoots (debugger.js:110726)
    at Scopes.render (debugger.js:110753)
    at debugger.js:75460
    at measureLifeCyclePerf (debugger.js:74741)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (debugger.js:75459)
    at ReactCompositeComponentWrapper._renderValidatedComponent (debugger.js:75486)
    at ReactCompositeComponentWrapper.performInitialMount (debugger.js:75028)
    at ReactCompositeComponentWrapper.mountComponent (debugger.js:74924)
    at Object.mountComponent (debugger.js:37299)
    at ReactCompositeComponentWrapper.performInitialMount (debugger.js:75037)
debugger.js:92034 Uncaught ReferenceError: services is not defined
    at setTimeout (debugger.js:92034)
setTimeout @ debugger.js:92034
setTimeout (async)
(anonymous) @ debugger.js:92028
action @ debugger.js:90020
(anonymous) @ debugger.js:79790
newSource @ debugger.js:89412
aProto.emit @ debugger.js:59122
onPacket @ debugger.js:59997
DevToolsUtils.executeSoon.DevToolsUtils.makeInfallible @ debugger.js:86432
(anonymous) @ debugger.js:40465
setTimeout (async
executeSoon @ debugger.js:40480
_onJSONObjectReady @ debugger.js:86428
JSONPacket.read @ debugger.js:87016
_processIncoming @ debugger.js:86359
(anonymous) @ debugger.js:86311
(anonymous) @ debugger.js:40465
```

**Comment by Anzumana** [comment] 2017-10-04 09:41
As suggested in the community call i 
updated yarn to 0.28.4 and node to v8.6.0 issue persists :/
@jasonLaster 
@codehag 
@nyrosmith 
Any steps i can take to tackle this issue further?

**Comment by Anzumana** [comment] 2017-10-05 08:33
i just checked i have the same behaviour with our todo backbone default example

**Comment by nyrosmith** [comment] 2017-10-05 08:46
@Anzumana  Can you paste the output of `npm ls -g --depth=0`
Maybe you have installed something global that interferes with the repo.

**Comment by jasonLaster** [comment] 2017-10-05 13:12
@nyrosmith @Anzumana can we close?

**Comment by nyrosmith** [comment] 2017-10-05 15:45
Yep. I'll close it

**Closed by nyrosmith** 2017-10-05 15:45 UTC
Labels: in progress
