### ISSUE TITLE
Feature - Add an option to change devtools font size (or zoom) with a mousewheel

### ISSUE THREAD

**Issue by eladcandroid** [devtools-html/debugger.html#4736] opened 2017-11-19 08:22 UTC

**Comment by jasonLaster** [comment] 2018-01-25 01:37
Hi, thanks for the feature request. I'm closing this issue and moving to the [enhancements](http://github.com/devtools-html/debugger.html/projects/5) board. 

* We will hopefully be able to prioritize it in the near future. 
* The issue is closed temporarily, but feel free to continue discussing here

**Closed by jasonLaster** 2018-01-25 01:37 UTC
Labels: not-available
