### ISSUE TITLE
Devtools open on debugger pane hangs Firefox on page refresh

### ISSUE THREAD

**Issue by bwhitty** [devtools-html/debugger.html#3736] opened 2017-08-21 19:09 UTC
Firefox version: 56.0b3 (64-bit) (dev edition)
MacOS: 10.12.6 (16G29)
Installed addons: ublock origin, lastpass, react devtools, redux devtools, gecko profiler

The following traces are from just refreshing one of the pages (network caching disabled).

With devtools open on the debugger panel: https://perfht.ml/2vSYpDo
With devtools open on the network panel: https://perfht.ml/2vSKrRX
With devtools closed: https://perfht.ml/2vSKfSJ

This is running in development mode for an app I work on. It has multiple 2 main bundles ranging from 5MB to 18MB. It's built with Webpack 3.3 (no scope-hoisting), and has ~2100 distinct modules. Source maps are Webpack's `eval-source-map`.

Anecdotally, I was using the debugger faithfully on Firefox dev edition 55 albeit with a bit of lag when searching for files upon page refresh, but it has regressed significantly upon updating to 56.

Let me know if those perf reports work out or if you'd like me to do more profiling. Thanks a lot for the awesome tooling!

**Comment by codehag** [comment] 2017-08-21 19:19
Thanks for the report! If I got it right, this is happening in the panel for 56, do you have a test case we can try out?

**Comment by bwhitty** [comment] 2017-08-21 19:26
Correct, this is happening for FF 56. Perf is decidedly different based on which devtool panel is open, with the debugger grinding the entire browser to a halt. Unfortunately this is an internal application I can't share. I'm not entirely sure how to create a replication with the same size as the main bundles of this app. I am presuming that to be causing the issues.

**Comment by codehag** [comment] 2017-08-21 19:28
ok, thanks for the info. We will investigate and get back to you :)

**Comment by jasonLaster** [comment] 2017-09-05 14:33
@bwhitty i'm going to close this as it is not something that we can "fix" per-se. We take perf seriously though and are always looking at improving our start up time. Thanks for sharing

**Comment by bwhitty** [comment] 2017-09-05 21:00
Thanks @jasonLaster. Could I possibly get some more information on what the root cause was and why it's a wontfix? I had to switch to Chrome to work on this product, and it handles everything gracefully. Don't take that as a dig, as it isn't, it's just more information that this isn't, for instance, some insane anomaly of a project.

**Comment by codehag** [comment] 2017-09-05 21:02
@bwhitty is this a large file bug? it looks from your description like it is. If that is the case it *might* be fixed. Do you have a test page we can take a look at?

**Comment by bwhitty** [comment] 2017-09-05 23:08
@codehag Awesome! It's quite possible it's a large file issue as the bundle and source map could be enormous. I will check again with Nightly once #3885 gets released. Would that fix be integrated tonight? (sorry, not sure what Nightly build/release process is like)

**Comment by ochameau** [comment] 2017-09-15 08:24
> @bwhitty i'm going to close this as it is not something that we can "fix" per-se.
??

The profiles @bwhitty gave are really actionnable.
Did you tried looking at the first one related to debugger?
https://perfht.ml/2vSYpDo
 - Select "Main thread", i.e. the first timeline (that's where the debugger UI lives)
 - In the call tree, see the first line? i.e. `exports.makeInfaillible`
    expand this 4 or 5 times, you will see `newSource` from `debugger.js`
 - Now expand this a lot, you will go through a lot of React stacks, but will also find debugger frames

Hopefully this will help you understanding what is slow.

This slowness is very easily reproducible on slack, just reload it and see your browser freeze if you have the debugger opened.

**Comment by ochameau** [comment] 2017-09-18 15:30
> In the call tree, see the first line? i.e. exports.makeInfaillible expand this 4 or 5 times, you will see newSource from debugger.js

From this you could see that `SourcesTree.componentWillReceiveProps` is slow.
Mostly because of immutable.js. It see a 3x win if I replace it with a naive manual check.

See this patch (sorry, it is against the webpack bundle):
https://bugzilla.mozilla.org/page.cgi?id=splinter.html&bug=1399242&attachment=8909337

Also, we call a url module helper too many times. We shoud avoid calling it especially in the hot codepaths. Note that we should be using web "URL" constructor instead of this.
https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

**Comment by codehag** [comment] 2017-09-28 10:50
@ochameau thanks! I will translate this into a pr against the git repo

**Comment by sneakyfildy** [comment] 2017-12-13 13:54
firefox debugger is impossible to use and firebug is not available. too bad poor firefox

**Comment by codehag** [comment] 2017-12-13 15:27
@sneakyfildy so sorry the debugger has been slow for you! we recently rewrote the debugger and are now working on some of the performance issues related to webpack and angular cli. Please tell us a little bit about your application and its build tools and hopefully we can make it fast for you in the near future.

**Comment by sneakyfildy** [comment] 2017-12-13 15:52
@codehag Dunno, the application is regular size. 350KB business logic, 560KB vendor bundle. AngularJS 1.5 packed by webpack. Super-fast debugging with chrome dev-tools and extremely laggy in firefox. Memory seems to be enough.
The funniest thing that the other project source in our company, which is HUGE (super-huge and bundled in one massive package logic+vendor+styles, also angularJS+webpack) cannot be even opened in... chrome debugger, while working *alright* in firefox (firefox is even able to beautify sources).
This is very strange.

**Comment by codehag** [comment] 2017-12-13 16:00
@sneakyfildy thanks for the information. We had a report of issues with angular sites on novemeber 16th: https://github.com/devtools-html/debugger.html/issues/4705

and we have resolved it with the three pull requests mentioned in that issue. This may or may not improve the performance you are seeing but we will investigate further.

The fix for this bug will be released on nightly some time this week, I will get in touch once it does -- however if you do not see an improvement in your smaller application, please get in touch with us again and we will dig deeper.

@jasonLaster can you rope jovan in?

**Comment by TitanNano** [comment] 2017-12-14 08:22
I think the main problem with our project was that we are using Angular2+ in JIT mode which creates additional inline source maps while bootstrapping the application. 

Angular 1.x doesn't do anything like this, so I wonder what could cause this. @sneakyfildy what is the main difference between the two apps you mentioned? Are they both built with the same Webpack version? Are you transpiling your code? (i.e. typescript to ES5, ES2015 or ES2015 to ES5) Do you build source maps?

**Comment by wldcordeiro** [comment] 2018-01-25 03:04
Any update here?

**Comment by jasonLaster** [comment] 2018-03-07 22:50
Hey @bwhitty @TitanNano how does nightly feel for you now?

**Comment by jasonLaster** [comment] 2018-03-07 23:06
Okay, I did a bit of digging and changing webpack's `devtool` setting to `eval-source-map`. Is kind of an evil case for us

STR:
1. git clone debugger.html
2. yarn 
3. edit `node_modules/devtools-launchpad/webpack.config.js` so that `webpackConfig.devtool = "eval-source-map";`

Here are some screenshots of this perf [profile](https://perfht.ml/2FjzzmD)

The take away is that our redux batching is not working the way it should in this case because there are a ton of `updateTree` calls which tells me we are aggressively re-rendering the tree. We can likely fix our redux newSources logic to avoid this.

![Screen Shot 2018-03-07 at 5.57.49 PM.png](https://shipusercontent.com/357df5efe92b15c1142f7f55eafe96f9/Screen%20Shot%202018-03-07%20at%205.57.49%20PM.png)
![Screen Shot 2018-03-07 at 5.56.41 PM.png](https://shipusercontent.com/dd4fdfb11235dda272f25e05461611b6/Screen%20Shot%202018-03-07%20at%205.56.41%20PM.png)


---

For fun i took a look at chrome and they also fetch all the maps when they see the sources. They slow down, but not as badly so we should be able to fix this. Debugger Inception ftw :)

![Screen Shot 2018-03-07 at 6.05.28 PM.png](https://shipusercontent.com/b2ec00e25507533f1ef4adafaa9613f7/Screen%20Shot%202018-03-07%20at%206.05.28%20PM.png)

**Comment by bwhitty** [comment] 2018-03-08 00:24
Hey @jasonLaster thanks for the ping. Running `60.0a1 (2018-03-07)` I get very high CPU and the debugger pane takes ~30 seconds to open. No more hanging the browser, though.

**Comment by jasonLaster** [comment] 2018-03-08 01:41
haha - sounds about like what i'd expect :)

We'll look into this soon, definitely before 61

**Closed** 2018-03-08 18:41 UTC
Labels: bug, panel, performance

**Comment by arcman77** [comment] 2018-03-19 20:29
I too am experiencing this issue. In my case, I have a vue app running, and if open the console and attempt to refresh, it will hang there indefinitely until I close the console. I am doing some bundling with webpack and there is a source map, but it fails to load.

**Comment by jasonLaster** [comment] 2018-03-19 20:33
@arcman77 can you try https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly and let us know if it still occurs.

**Comment by arcman77** [comment] 2018-03-19 20:36
@jasonLaster sure thing. I'll try it right now.

**Comment by grdinic-ua** [comment] 2018-10-03 18:48
Darn: On a page that works fine in Chrome dev tools, same issue here -- only now in 62 the debugger has become *completely* unresponsive, as in the page hangs *indefinitely* as soon as the Developer tools are opened. By hang I mean literally nothing works on the page, buttons, links, etc. 

Did some testing and narrowed it down to have embedded YouTube and Vimeo videos on the page as being the cause. Once those guys were removed all works again.

**Comment by loganfsmyth** [comment] 2018-10-03 19:57
@grdinic-ua If you can reproduce the issue on Firefox Nightly too, probably best to file a new issue with a page to reproduce or more info so we can reproduce on our own.

**Comment by arecvlohe** [comment] 2019-03-20 14:58
I just started noticing this on FFDE 67. Hadn't used debugger before but it definitely slows down and hangs for a while before proceeding. I will have to switch to Chrome for using debugger.

**Comment by bwhitty** [comment] 2019-03-20 17:18
Agreed. Just upgraded to FF67 developer edition and had the dev tools hang the entire browser. Possibly some regression here?
