### ISSUE TITLE
[Editor] window displays a "undefined" instead of the script content.

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#6549] opened 2018-06-26 06:26 UTC
1. With Firefox Nightly 63.0a1 (2018-06-25) (64-bit) on macOS 10.13.5 (17F77)
2. Go to https://cointelegraph.com/news/jp-morgan-chase-makes-surprising-announcement-may-add-bitcoin-futures
3. Open debugger in developer tools 
4. navigate to https://cointelegraph.com/assets/js/script.js?1529942528 in the sources panel.

Actual:
The script window displays "undefined"

Expected:
The script.

The script is 200 in the network panel.

```http
HTTP/2.0 200 OK
date: Tue, 26 Jun 2018 06:26:02 GMT
content-type: application/javascript
cache-control: max-age=315360000
cf-railgun: 4564f5ae60 stream 0.000000 0200 e6be
etag: W/"5b311200-b5bcb"
expires: Thu, 31 Dec 2037 23:55:55 GMT
last-modified: Mon, 25 Jun 2018 16:02:08 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 430d999b7d3b943f-NRT
content-encoding: br
X-Firefox-Spdy: h2
```

**Comment by darkwing** [comment] 2018-06-29 16:41
Thank you for the report and screenshot @karlcow !

**Comment by jasonLaster** [comment] 2018-07-06 13:46
Hmm, i see it when i go there

![screen shot 2018-07-06 at 9 45 56 am](https://user-images.githubusercontent.com/254562/42382168-741aea2e-8101-11e8-887f-96dbddac683c.png)

**Comment by janodvarko** [comment] 2018-07-06 14:04
I can easily reproduce the bug on Win10
Honza

**Comment by manu-4216** [comment] 2018-08-02 13:29
As a workaround, in "Debugger" section, I disabled the settings  "Automatically Black Box Minified Sources" and "Auto prettify Minified Sources". This worked for me.

**Comment by jasonLaster** [comment] 2018-08-02 15:32
thanks @manu-4216

**Comment by darkwing** [comment] 2018-12-10 20:20
@janodvarko Could you try this again on your Win 10 machine?

**Comment by janodvarko** [comment] 2018-12-11 14:10
I can't see the `scripts.js` file in the Sources panel anymore. There are: app.js, runtime.js and vendors.js
When selecting these files (under `assets/js`) I can properly see their content.

Honza

**Comment by darkwing** [comment] 2019-02-11 18:52
I'm closing this for now since we can't seem to reproduce, but feel free to reopen if it happens again.

**Closed by darkwing** 2019-02-11 18:52 UTC
Labels: bug, not-actionable
