### ISSUE TITLE
[CallStack] Long function names are not shown completely in the call stack view

### ISSUE THREAD

**Issue by julienw** [devtools-html/debugger.html#3215] opened 2017-06-23 15:55 UTC
See attachment: ![capture d ecran de 2017-06-23 17-52-54](https://user-images.githubusercontent.com/454175/27490033-164ccf22-583d-11e7-9b3c-816f5ca5097f.png)

I'm on Linux in case this is important.

**Comment by julienw** [comment] 2017-06-23 16:01
What's especially weird is that the ellipsis is at the start and not at the end... I'm using the french locale.

**Comment by juliandescottes** [comment] 2017-08-22 17:52
Issue #3259 was closed as duplicate of this one. Attaching my screenshot here, because even if both issues deal with function names being truncated, the STRs are different. 

![image](https://user-images.githubusercontent.com/1141550/29579149-243c0148-8772-11e7-9e52-72823ec364c2.png)

The issue here occurs when there is not enough space to display both the function name and the script location. The function name is truncated, making it difficult to understand the call stack.

**Comment by jasonLaster** [comment] 2017-12-15 15:56
@violasong what do you think?

**Comment by violasong** [comment] 2017-12-22 01:15
I still like the ideas mocked up in #3380 - truncating the filename with ellipsis, or (assuming filenames are worth the vertical space), breaking filename onto second row.
https://github.com/devtools-html/debugger.html/issues/3380#issuecomment-317901959

If we truncate, user should be able to hover to view a tooltip that contains the full name/filename.

**Comment by jasonLaster** [comment] 2017-12-22 13:56
Yeah, i feel like we should switch to truncating by the filename for now and show the full path with a tooltip. 

I'd like to revisit the pause state UI in 2018 and design a more opinionated call stack.

**Comment by jasonLaster** [comment] 2018-03-14 21:38
Moving this to the icebox, we can re-evaluate at the start of the next release

**Closed by jasonLaster** 2018-03-14 21:38 UTC
Labels: bug
