### ISSUE TITLE
Resize cursor and splitter position are shifted when the bookmarks sidebar is opened and dragging splitter

### ISSUE THREAD

**Issue by magicp-github** [devtools-html/debugger.html#856] opened 2016-10-02 14:13 UTC
Regression range:
https://hg.mozilla.org/integration/fx-team/pushloghtml?fromchange=500496dfefccc73d1f87ff912563a8ee1afe8e91&tochange=cdbfde37e79590e4c188ba854ab0b1612402e338

**Comment by wldcordeiro** [comment] 2016-10-02 19:07
Since the SplitBox comes from m-c could it be a fix applied upstream @jlongster @jasonLaster? Or maybe our usage of it is wrong.

**Comment by magicp-github** [comment] 2016-10-12 15:10
This bug still reproduce in latest Nightly Build ID (20161012030211)

**Comment by jasonLaster** [comment] 2016-10-12 15:44
@magicp-github should be fixed when we update the debugger on nightly soon. Sorry, there's some lag between a patch landing on github and being shown in nightly

**Comment by magicp-github** [comment] 2016-11-12 07:52
Hello @jasonLaster,
This bug still reproduce in latest Nightly build (20161111030203). Any update?

**Comment by jasonLaster** [comment] 2016-11-13 03:53
I'll look into this on monday

**Comment by jasonLaster** [comment] 2016-12-30 17:01
This is a dupe of #1378

**Closed by jasonLaster** 2016-12-30 17:01 UTC
