### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by nesk** [devtools-html/debugger.html#936] opened 2016-10-15 21:30 UTC
`npm install` fails since the `devtools-*` packages have been [added to the dependencies](https://github.com/devtools-html/debugger.html/commit/4a0e823f8ea6ea493f6516dd7ba55e3e4412f946#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R55).

```shell
❯ npm install        
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.8.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/devtools-network-request
npm ERR! 404 
npm ERR! 404  'devtools-network-request' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'debugger.html'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     ./debugger.html/npm-debug.log
```

**Comment by jasonLaster** [comment] 2016-10-16 00:56
Thanks for the report @nesk. 

The issue is likely a question of whether lerna is installed correctly. 

Could you check:
1. Is your branch up to date? 
2. If lerna is installed

**Comment by nesk** [comment] 2016-10-16 16:46
My branch is up to date. I just tried by wiping the project off and ran these commands:

```shell
❯ npm install --global lerna@prerelease
❯ npm install
```

And I get the same error, I event tried running `lerna bootstrap` before running `npm install` bu it still doesn't work.

**Comment by jasonLaster** [comment] 2016-10-16 16:58
Thanks. We're actually using a forked version jasonlaster/lerna. 

I noticed yesterday that there's another issue with the toolbox's webpack.config. On line 55, I believe, it should require the debuggers webpack config ../../../webpack.config

**Comment by Pomax** [comment] 2016-10-16 17:16
note that the error mentions that https://www.npmjs.com/package/devtools-network-request does not exist, which is true - nothing was published to npm with that name (yet?)

**Comment by wldcordeiro** [comment] 2016-10-16 17:30
@Pomax that isn't directly related. Since we use lerna it resolves these inner packages. and "installs" them, I think the idea is to publish to npm when we get to a more stable state and there isn't as much interdependency.

**Comment by wldcordeiro** [comment] 2016-10-16 17:31
@jasonLaster that line seems to use a function to resolve the configs https://github.com/devtools-html/debugger.html/blob/master/packages/devtools-local-toolbox/webpack.config.js#L54

**Comment by jasonLaster** [comment] 2016-10-16 17:32
Yes. It needs to resolve to the debuggers config. Could you PR that fix?

**Comment by wldcordeiro** [comment] 2016-10-16 17:58
@jasonLaster yeah I can, it seems like that function actually resolves to the debugger's `local.json` should it instead resolve to the webpack config?

**Comment by Pomax** [comment] 2016-10-16 18:01
@wldcordeiro in that case one important question is "which version of node/npm is being used" node4 still uses npm2 which installs packages in a nested hierarchy, whereas node6 with npm3 installs everything in a flat directory structure as much as possible, which can impact projects in surprising ways (might not be related, but it might be, in which case lerna might need to check which version npm it's dealing with)

**Comment by wldcordeiro** [comment] 2016-10-16 18:05
@Pomax I wouldn't know for certain, on Lerna's repo and webpage they don't mention an npm 3 requirement, ideally that would be something they mentioned though.

**Comment by Pomax** [comment] 2016-10-16 18:11
Yeah, it doesn't look like https://github.com/lerna/lerna/blob/master/package.json has an `engines` section to make it clear what it relies on. I've filed https://github.com/lerna/lerna/issues/378 for them to consider adding one.

**Comment by wldcordeiro** [comment] 2016-10-16 18:12
Thanks @Pomax I'm still trying to reconcile my branches and get it working with the new mono-repo workflow myself so I'll update this issue and submit a PR when I can get it figured out if @jasonLaster doesn't beat me to it. 😄

**Comment by wldcordeiro** [comment] 2016-10-16 20:09
Researching stuff has lead me to believe `npm preinstall` doesn't work properly with `npm` v3.x as nuking node_modules and trying `npm install` always fails with the 404s listed in the issue. So to alleviate things here we will need to document that installing the dependencies for the debugger should just be done by running `./bin/preinstall` (which we could rename to `./bin/install` or something)

NPM issue:
https://github.com/npm/npm/issues/10379

**Comment by jasonLaster** [comment] 2016-10-18 20:39
@nesk @Pomax mind giving this another try. I believe it should be fixed :)

Closing this issue preemptively, feel free to re-open it.

**Closed by jasonLaster** 2016-10-18 20:39 UTC
