### ISSUE TITLE
yarn run firefox, when it can't find firefox

### ISSUE THREAD

**Issue by sole** [devtools-html/debugger.html#1761] opened 2017-01-19 17:55 UTC
I get this error:

```
$ ./node_modules/.bin/start-firefox --start --location https://devtools-html.github.io/debugger-examples/
(node:27908) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not locate Firefox on the current system
(node:27908) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

And then that's it.

My Firefox(es) binaries are not in the default Mac OS app location (`/Applications`) but in my `~/Applications`. I guess this is an issue related to selenium webdriver? I can investigate this, but I figured it would be worth to at least log the issue just in case someone else is encountering this too.

This is right after installing the project, I'm just following the instructions on https://github.com/devtools-html/debugger.html#getting-setup

**Comment by Garbee** [comment] 2017-01-20 13:10
Looks like we may just need to update the Selenium we use. The [current master](https://github.com/SeleniumHQ/selenium/blob/313e0911ccf584bcd965ff5f71f0ad17459ff2cb/dotnet/src/WebDriver/Firefox/Internal/Executable.cs#L178) has a fix in place for this. However the commit this is from goes back [four years](https://github.com/SeleniumHQ/selenium/blame/master/dotnet/src/webdriver/Firefox/Internal/Executable.cs#L170). So either we are using something very dated or the original fix isn't working as expected. It looks like there is [an open issue](https://github.com/seleniumhq/selenium/issues/1437) about just this upstream. It would be best to follow up there so the issue is fixed for everyone using Selenium.

**Comment by sole** [comment] 2017-01-20 15:17
@jasonLaster said in IRC that it might be an issue in selenium https://github.com/devtools-html/devtools-core/issues/101

I've no experience with Selenium so I can't really say...

I suggested that another option is to maybe provide a way for the user to specify the path to the Firefox binary when running `yarn run firefox`. This should enable testing with different versions. 

Jason also suggested adding an option into configs.local to manually adding the path to the binary.

In the meantime I will need to put a `Firefox.app` on `/Applications` to get the debugger to work, right?

**Comment by Garbee** [comment] 2017-01-20 15:24
Try just symlinking it to `/Applications` instead of outright moving it. That should do the trick for you without incurring problems anywhere else.

Warning: I am not a MacOS user, this is just a guess based on my Linux experience and how similar the underlying systems are.

**Comment by jasonLaster** [comment] 2017-01-26 01:05
closing as it's filed in core, where it can be fixed

**Closed** 2017-01-26 01:05 UTC
Labels: bug

**Comment by sole** [comment] 2017-02-14 09:34
Confirming that symlinking it with

```bash
ln -s /Users/sole/Applications/Firefox.app /Applications/Firefox.app
```

allows me to launch Firefox via Launchpad
