### ISSUE TITLE
Standardize colors with base16

### ISSUE THREAD

**Issue by zenorocha** [devtools-html/debugger.html#3537] opened 2017-08-02 20:32 UTC
Hey everyone,

It seems to me that the dark theme used here was inspired by [Dracula](https://draculatheme.com). I created this project few years ago and today it's one of the most used color schemes out there. So I'm wondering if you're interested in following the [color palette](https://github.com/dracula/dracula-theme/#color-palette) we defined there. I believe it would be a very nice improvement and I could try to help.

Let me know if this is something you would like to do. Keep up with the good work!

/cc @jasonLaster

**Comment by jasonLaster** [comment] 2017-08-02 20:35
Hey @zenorocha! Great timing. We've been discussing color palettes a lot recently.

Would you mind hopping in our slack room so we can discuss: https://devtools-html-slack.herokuapp.com/

The dream would be to adopt a system where users could choose a theme firefox dark, light, firebug, dracula, one dark, ... etc.

**Comment by jasonLaster** [comment] 2017-08-02 21:28
Here's a sketch [branch] that creates a theme system based on base16 with a couple new themes (dracula, one-light).

[branch]:https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:themes?expand=1

The concept is that we can switch our variables to a base(0-16) system so that the firefox themes don't change, but we can begin to support new themes as well.

![](http://g.recordit.co/xLoFjiO5gl.gif)

**Comment by jasonLaster** [comment] 2017-08-02 21:54
React DevTools built there themes off of base16 with some extra sauce:

https://github.com/facebook/react-devtools/blob/master/frontend/types.js#L83-L123

https://github.com/facebook/react-devtools/blob/master/frontend/Themes/Themes.js

CC @bvaughn

**Comment by bvaughn** [comment] 2017-08-02 21:56
It would be lovely if we could share themes somehow between both DevTools 😄  Probably a pipe dream though.

**Comment by jasonLaster** [comment] 2017-08-02 21:57
perhaps we can. All we'd have to do is write the themes to a style tag...

**Comment by zenorocha** [comment] 2017-08-02 22:05
That would be awesome!

**Comment by jasonLaster** [comment] 2017-08-03 00:03
I updated the branch a bit so that we can pull in react devtools themes and alternate through the themes with this new console command `updateThemes`

There's now a new repo [devtools-themes](https://github.com/jasonLaster/devtools-themes) that we can import.

![](http://g.recordit.co/xekfVoWT0p.gif)

**Comment by bvaughn** [comment] 2017-08-03 01:36
😲 😁

**Comment by jasonLaster** [comment] 2017-08-03 03:56
Just created a new [branch], which uses `devtools-themes` and aliases the existing variables as opposed to replacing them. 

* The diff is much smaller 
* we can likely land it incrementally as well, which is a huge win.
* and we can play with the individual variable mappings `theme-comment: var(--base00);` without getting confused did `--base00` map to theme-comment or theme-sidebar?

https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:themes2?expand=1

**Comment by jasonLaster** [comment] 2017-10-27 20:27
Closing this issue and moving to the [enhancements](github.com/devtools-html/debugger.html/projects/5) board. 

* We will hopefully be able to prioritize it in the near future. 
* The issue is closed temporarily, but feel free to continue discussing the issue

**Closed by jasonLaster** 2017-10-27 20:27 UTC
Labels: enhancement, in progress
