### ISSUE TITLE
Outline view does not jump to the function

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/debugger.html#4780] opened 2017-11-23 10:45 UTC
The outline view lists the methods in the file, but clicking on a method does not scroll to the method in the editor.

![debugger-outline-view-broken](https://user-images.githubusercontent.com/1141550/33169098-a31e600e-d043-11e7-9220-ce3e8662cdd9.gif)

Works with any source file but here are some STRs:
- go to http://firefox-dev.tools/debugger-examples/examples/todomvc/
- open debugger
- open source app-view.js
- switch to outline view 
- click on a method

ER: should jump to the method definition
AR: nothing happens

Has been broken for a while but I thought this was already tracked here.

**Comment by jasonLaster** [comment] 2017-11-23 17:29
We fixed it in GH. The next release should have it

**Comment by nyrosmith** [comment] 2017-11-23 18:40
This is a duplicate of https://github.com/devtools-html/debugger.html/issues/4616 and is already fixed.

**Closed by nyrosmith** 2017-11-23 18:40 UTC
Labels: not-available
