### ISSUE TITLE
[PrettyPrint] Prettify minified inline <script> tag content

### ISSUE THREAD

**Issue by captainbrosset** [devtools-html/debugger.html#4887] opened 2017-12-08 13:54 UTC
This comes from this bugzilla report: https://bugzilla.mozilla.org/show_bug.cgi?id=1010150

Here is a test case: https://bug1010150.bmoattachments.org/attachment.cgi?id=8422335
- open this url
- open the debugger
- select the HTML page in the tree

This HTML page has  `<script>` nodes. One of them contains minified code, and I can't pretty-print it.

It would be very useful to be able to do so.

Various WebCompat people have requested this, as you can see in this comment: https://bugzilla.mozilla.org/show_bug.cgi?id=1010150#c15

**Comment by AnshulMalik** [comment] 2018-01-06 05:15
Yep, this will very useful.

**Comment by jasonLaster** [comment] 2018-01-25 02:01
Closing this issue and moving to the [enhancements](http://github.com/devtools-html/debugger.html/projects/5) board. 

* We will hopefully be able to prioritize it in the near future. 
* The issue is closed temporarily, but feel free to continue discussing the issue

**Closed by jasonLaster** 2018-01-25 02:01 UTC
Labels: enhancement

**Comment by yoshimo** [comment] 2018-02-16 19:27
Would be worth expanding this to html in general.
Often there is a lot of tabs and whitespace and new lines that make it difficult to read the source of a site.
Hiding comments plays into this as well.
