### ISSUE TITLE
Customizable Keyboard Shortcuts

### ISSUE THREAD

**Issue by Garbee** [devtools-html/debugger.html#1178] opened 2016-11-13 18:14 UTC
One of the big requests for a while now for DevTools has been [customizable keyboard shortcuts](https://bugs.chromium.org/p/chromium/issues/detail?id=174309) so developers can change how they get around the system quickly.

Since this project is starting from scratch, it would be very beneficial if we could come up with a good way to allow this from the start. This enhancement would give developers the control they want while also keeping all assigned shortcuts available in an easy way to lookup to reference what is in use later.

**Comment by jasonLaster** [comment] 2016-11-16 19:47
I moved this to our enhancements project https://github.com/devtools-html/debugger.html/projects/5

And I'm closing it now because we'll be able to revisit this when we work on enhancements in Q1.

**Closed by jasonLaster** 2016-11-16 19:47 UTC
Labels: enhancement

**Comment by jbhoosreddy** [comment] 2016-11-16 19:49
One note, I'd like to leave here is that there should be some way to prevent conflicting from other Firefox or system shortcuts, because that just messes everything. I've been affected by that before.

**Comment by jasonLaster** [comment] 2016-11-16 19:54
good point.

As a side-note, i hope the conversation doesn't stop because the issue is closed! It's closed because open issues should be actionable within two sprints (4 weeks).
