### ISSUE TITLE
[Search] Editor doesn't scroll with down keys

### ISSUE THREAD

**Issue by AnshulMalik** [devtools-html/debugger.html#2370] opened 2017-03-14 15:36 UTC
When the search bar is open(visible), and user try to move cursor inside editor, the cursor on reaching the bottom, comes back to the search box instead of scrolling the editor.
![peek 2017-03-14 21-00](https://cloud.githubusercontent.com/assets/7821757/23908422/fa6e89fe-08f9-11e7-94a3-8178f9d7cf72.gif)

**Comment by irfanhudda** [comment] 2017-03-22 14:02
@AnshulMalik Can you reproduce this now? This might have been fixed in one of the previous commits.

**Comment by irfanhudda** [comment] 2017-03-22 14:54
This is the GIF after I've tried to reproduce this.
![bug](https://cloud.githubusercontent.com/assets/1755089/24204084/6c6d7e86-0f3d-11e7-882f-bfd373116f5b.gif)

Looks like there is new issue

**Comment by jasonLaster** [comment] 2017-03-23 03:02
One thought that might not help is there is a CSS sticky property we might be able to use. We used it for the command bar effectively :)

**Comment by jasonLaster** [comment] 2017-03-24 20:10
I'm going to close this as it looks like we're now looking at #2424 which is separate

**Closed by jasonLaster** 2017-03-24 20:10 UTC
Labels: bug
