### ISSUE TITLE
[SourceTree] File icon is missing

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#7887] opened 2019-02-06 01:20 UTC
The source tree file icon is missing in the source tree

<img width="221" alt="screen shot 2019-02-05 at 5 20 16 pm" src="https://user-images.githubusercontent.com/254562/52315093-545a7f80-296a-11e9-82d1-c121b3cc2ae1.png">

**Comment by errietta** [comment] 2019-02-06 19:05
@jasonLaster I cannot reproduce.
![image](https://user-images.githubusercontent.com/134585/52366658-33655d80-2a42-11e9-9344-826c86192ed3.png)

**Comment by fvsch** [comment] 2019-02-07 09:02
If merged, #7890 will touch that a bit too.

**Closed** 2019-02-12 21:20 UTC
Labels: in progress
