### ISSUE TITLE
Dark Theme - Accordion Header Color Tweaks

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/debugger.html#999] opened 2016-10-25 20:53 UTC
Hovering over an accordion header produces a white background. 

![screenshot_20161025_145322](https://cloud.githubusercontent.com/assets/580982/19703889/cb013ec8-9ac2-11e6-8be3-18bb549546ba.png)

**How do you change themes locally?** You can edit the theme locally [here](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#themes)

**How do we fix these?** Add CSS overrides in the different components. Here's an example of how we could fix the right sidebar commands.

``` diff
diff --git a/public/js/components/RightSidebar.css b/public/js/components/RightSidebar.css
index 5f5f8b4..794aa0d 100644
--- a/public/js/components/RightSidebar.css
+++ b/public/js/components/RightSidebar.css
@@ -40,6 +40,10 @@ html[dir="rtl"] .command-bar {
   transition: opacity 200ms;
 }

+:root.theme-dark .command-bar > span {
+  stroke: var(--theme-body-color);
+}
+
 html:not([dir="rtl"]) .command-bar > span {
   margin-right: 0.7em;
 }
```

**How do I choose the right color?** Hmm, it's up to you. We have a list of variables [here](https://github.com/devtools-html/debugger.html/blob/master/packages/devtools-local-toolbox/public/js/lib/themes/variables.css). What I do is look for similar colors in the app and then see what variable it uses in the inspector.

**Comment by ajstrand** [comment] 2016-10-27 15:59
@wldcordeiro I wouldn't mind tackling this issue. I probably wouldn't be tackle it until this weekend however.

**Comment by wldcordeiro** [comment] 2016-10-27 16:16
@ajstrand thanks! That won't be a problem at all.

**Comment by helenvholmes** [comment] 2016-10-27 20:12
Whoops, didn't see that @ajstrand had requested it!

**Comment by ajstrand** [comment] 2016-10-31 01:21
@wldcordeiro I've been trying to get the project up and running on my machine, but I've been having issues when trying to do `npm run firefox`. 

This is the error that I get 
```
> debugger.html@0.0.6 firefox /home/ajstrand/Documents/debugger.html
> node bin/firefox-driver --start

/home/ajstrand/Documents/debugger.html/node_modules/selenium-webdriver/lib/promise.js:2291
        throw error;
        ^

Error: Server terminated early with status 1
    at Error (native)
    at /home/ajstrand/Documents/debugger.html/node_modules/selenium-webdriver/remote/index.js:255:22
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/ajstrand/Documents/debugger.html/node_modules/selenium-webdriver/lib/webdriver.js:366:24)
    at createGeckoDriver (/home/ajstrand/Documents/debugger.html/node_modules/selenium-webdriver/firefox/index.js:497:27)
    at Driver (/home/ajstrand/Documents/debugger.html/node_modules/selenium-webdriver/firefox/index.js:605:14)
    at start (/home/ajstrand/Documents/debugger.html/bin/firefox-driver.js:42:18)
    at Object.<anonymous> (/home/ajstrand/Documents/debugger.html/bin/firefox-driver.js:47:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
From: Task: WebDriver.navigate().to(http://localhost:7999/todomvc)
    at Driver.schedule (/home/ajstrand/Documents/debugger.html/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
    at Navigation.to (/home/ajstrand/Documents/debugger.html/node_modules/selenium-webdriver/lib/webdriver.js:1042:25)
    at Driver.get (/home/ajstrand/Documents/debugger.html/node_modules/selenium-webdriver/lib/webdriver.js:832:28)
    at Object.<anonymous> (/home/ajstrand/Documents/debugger.html/bin/firefox-driver.js:48:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```
I can navigate to `localhost:7999` and see the various examples, but that doesn't help me with this predicament. 

I ran `npm install`, so that shouldn't be an issue here. 

I will note that I"m running `npm run firefox` in a separate terminal window after I've ran `npm start`. 

Any ideas on why `npm run firefox` isn't working? 

If it helps I'm running Ubuntu 16.04 in Virtual Box VM.

**Comment by jasonLaster** [comment] 2016-10-31 01:26
Sorry. NPM run Firefox isn't working now. Use the long command to start Firefox

**Comment by jasonLaster** [comment] 2016-10-31 01:35
@ajstrand here's the command i run: /Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin --start-debugger-server 6080 -P dev

**Comment by ajstrand** [comment] 2016-10-31 01:46
I got it working, thanks guys! I ended changing some of the settings in `about:config` .  Now I can actually start on fixing this.

**Comment by jasonLaster** [comment] 2016-10-31 03:44
Haha. Great. Hmm, our contributing docs touch on some of this but maybe you
can take a look and offer a suggestion. Also, of course I'll remove the
reference to npm run Firefox until et fix it

**Comment by ajstrand** [comment] 2016-11-01 00:41
@wldcordeiro or @jasonLaster I've come up with a fix for this issue and committed it to my fork, but `npm run lint` fails for me. 

And the strange thing is the error references js files, but I didn't touch those at all. 

Here's the error message 
```
> debugger.html@0.0.6 prepush /home/ajstrand/Documents/debugger.html
> npm run lint; node public/js/test/node-unit-tests.js --dots


> debugger.html@0.0.6 lint /home/ajstrand/Documents/debugger.html
> npm run lint-css -s; npm run lint-js -s


/home/ajstrand/Documents/debugger.html/public/js/components/Accordion.js
  18:14  error  Expected indentation of 6 spaces but found 13   indent
  54:15  error  Expected indentation of 12 spaces but found 14  indent

/home/ajstrand/Documents/debugger.html/public/js/components/App.js
  87:15  error  Expected indentation of 4 spaces but found 14  indent
  88:13  error  Expected indentation of 2 spaces but found 12  indent

/home/ajstrand/Documents/debugger.html/public/js/components/Expressions.js
  110:7  error  Expected indentation of 8 spaces but found 6  indent

/home/ajstrand/Documents/debugger.html/public/js/components/RightSidebar.js
  195:5  error  Expected indentation of 6 spaces but found 4  indent
  196:7  error  Expected indentation of 8 spaces but found 6  indent
  197:7  error  Expected indentation of 8 spaces but found 6  indent
  198:5  error  Expected indentation of 6 spaces but found 4  indent
  199:7  error  Expected indentation of 8 spaces but found 6  indent
  200:5  error  Expected indentation of 6 spaces but found 4  indent
  201:7  error  Expected indentation of 8 spaces but found 6  indent

/home/ajstrand/Documents/debugger.html/public/js/components/Sources.js
  39:15  error  Expected indentation of 4 spaces but found 14  indent

/home/ajstrand/Documents/debugger.html/public/js/components/SourceSearch.js
  96:15  error  Expected indentation of 4 spaces but found 14  indent
  97:15  error  Expected indentation of 4 spaces but found 14  indent
  98:13  error  Expected indentation of 2 spaces but found 12  indent

/home/ajstrand/Documents/debugger.html/public/js/components/SourcesTree.js
  68:21  error  Expected indentation of 6 spaces but found 20  indent
  69:21  error  Expected indentation of 6 spaces but found 20  indent

/home/ajstrand/Documents/debugger.html/public/js/components/utils/ManagedTree.js
  12:14  error  Expected indentation of 6 spaces but found 13  indent

/home/ajstrand/Documents/debugger.html/public/js/utils/sources-tree.js
  263:12  error  Expected indentation of 4 spaces but found 11  indent
  264:12  error  Expected indentation of 4 spaces but found 11  indent
  265:12  error  Expected indentation of 4 spaces but found 11  indent

✖ 22 problems (22 errors, 0 warnings)
```

Have you had reports of anyone else having this issue? 
I have the editorconfig and eslint plugins installed in Atom, so I'm surprised that these files would be messed up.

**Comment by jasonLaster** [comment] 2016-11-01 04:07
Yup. One other report. I'll look tomorrow

**Comment by helenvholmes** [comment] 2016-11-01 20:50
Closed via #1057.

**Closed** 2016-11-01 20:50 UTC
Labels: dark theme, difficulty: easy, in progress

**Comment by jasonLaster** [comment] 2016-11-01 20:51
Hi @ajstrand I'm sorry you're running into issues with npm lint.

I'd like to help if I can, but I'm not able to reproduce the linting issues. Feel free to stop by our IRC room in #devtools (look at the readme for instructions). or ping me at jason.laster.11@gmail.com and I can 'hangout and help fix it.

**Comment by ajstrand** [comment] 2016-11-02 01:16
@jasonLaster I managed to fix the issue. Some the indentation had gotten messed up in a few of the files and so I just had to go correct the affected files. I'll putting up my PR shortly.
