### ISSUE TITLE
Resuming from "Pause on exception" immediately pauses again in parent

### ISSUE THREAD

**Issue by loganfsmyth** [devtools-html/debugger.html#7681] opened 2019-01-08 00:24 UTC
Steps
1. Open devtools and enable pause on exception
2. Load https://plucky-sofa.glitch.me/ with snippet
	```
	function fn(){
	  throw new Error("way");
	}
	function fn2() {
	  fn();
	}
	function fn3() {
	  fn2(); 
	}
	fn3();
	```
3. Observed paused at `throw new Error("way");`
4. Press Resume

ER: 
Page should resume execution

AR:
Page resumes and immediately pauses again in the parent frame in `fn2`

**Comment by nmicht** [comment] 2019-02-10 02:57
I was not able to reproduce this error on current master latest commit [f4621c3](https://github.com/devtools-html/debugger.html/commit/f4621c3a170220dcb264a39edff4cdc62327b5d9)

@loganfsmyth can you please take a look again and update in case is necessary?

**Comment by jasonLaster** [comment] 2019-02-10 03:24
I think this was fixed in bugzilla...

**Comment by darkwing** [comment] 2019-02-11 20:21
This still occurs in Nightly.

**Closed by darkwing** 2019-02-11 20:21 UTC

**Comment by loganfsmyth** [comment] 2019-02-13 21:23
This is definitely a server issue, so I've refiled as https://bugzilla.mozilla.org/show_bug.cgi?id=1527744
