### ISSUE TITLE
Unable to toggle ( uncheck ) `pause on next Statement` button

### ISSUE THREAD

**Issue by tripurari001** [devtools-html/debugger.html#5380] opened 2018-02-09 18:46 UTC
Unable to toggle ( uncheck ) `pause on next Statement` button once it's selected
![image](https://user-images.githubusercontent.com/17466642/36044072-77342fae-0df7-11e8-8d10-139f859b5573.png)

**Comment by jasonLaster** [comment] 2018-02-09 21:01
dupe of #5125

**Closed by jasonLaster** 2018-02-09 21:01 UTC
Labels: not-available
