### ISSUE TITLE
[dark] gap in source search width

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3524] opened 2017-08-01 21:29 UTC
it looks like we allowed a gap to appear in between source search and the editor

<img src='https://shipusercontent.com/df3e2c2775b27b9714aecbb7f100ba06/Screen%20Shot%202017-08-01%20at%205.28.37%20PM.png' title='Screen Shot 2017-08-01 at 5.28.37 PM.png' width=417>

**Comment by adamki** [comment] 2017-08-12 22:43
Its been a while since I was able to open up this project. I'd love to take a shot at this.

**Comment by adamki** [comment] 2017-08-12 23:21
Hmmm. Not seeing this on mine. Any tips to reproduce?

**Comment by jasonLaster** [comment] 2017-08-13 03:31
strange, i saw it yesterday.

**Comment by adamki** [comment] 2017-08-13 05:44
Excellent. Ill dig in tomorrow

**Comment by adamki** [comment] 2017-08-14 17:25
So, there is a bit in `projectSearch.css` that sets the the width of `.search-container` to `calc(100% - 1px)`. This creates an actual gap between `search-container` and adjacent divs.

This gap of 1px looks to be used so that the `splitter` div can build some sort of vertical partition. However, it also allows for text from any underlying elements to show through this 1px gap. 

Any tips on how to close this gap? Unfortunately, setting the `.search-container` width to `calc(100%)` doesn't work too well as it ruins the splitter div.

**Comment by jasonLaster** [comment] 2017-08-14 17:40
Not sure. It'd be nice to compare other panes like the sources sidebar and
editor pane.

**Closed** 2017-08-15 20:11 UTC
Labels: difficulty: easy, in progress, theme: dark
