### ISSUE TITLE
yarn run test-all fails on Fedora 25 x86-64 and Mageia 6 x86-64 (also with nvm)

### ISSUE THREAD

**Issue by shlomif** [devtools-html/debugger.html#2381] opened 2017-03-15 11:03 UTC
Hi all!

On Fedora 25 x86-64 I am getting the following output from `yarn run test-all`. How can it be fixed?

```
yarn run v0.16.1
$ yarn run test; yarn run lint; yarn run flow 
yarn run v0.16.1
$ jest --forceExit 

 RUNS  ...breakpoints.js
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/shlomif/Download/unpack/firefox/debugger.html/assets/build/source-map-worker.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at process.<anonymous> (/home/shlomif/Download/unpack/firefox/debugger.html/node_modules/workerjs/requireworker.js:45:16)
    at process.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/shlomif/Download/unpack/firefox/debugger.html/assets/build/pretty-print-worker.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at process.<anonymous> (/home/shlomif/Download/unpack/firefox/debugger.html/node_modules/workerjs/requireworker.js:45:16)
    at process.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

[K
[1A
[K
[1A
 RUNS  ...breakpoints.js

[K
[1A
[K
[1A
 RUNS  ...breakpoints.js

[K
[1A
[K
[1A
 RUNS  ...breakpoints.js

[K
[1A
[K
[1A
 RUNS  ...breakpoints.js

[K
[1A
[K
[1A
 RUNS  ...breakpoints.js

[K
[1A
[K
[1A
 RUNS  ...breakpoints.js

[K
[1A
[K
[1A FAIL  actions/tests/breakpoints.js (6.768s)

 RUNS  ...breakpoints.js

[K
[1A
[K
[1A  ● breakpoints › should add a breakpoint

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at Timeout.callback [as _onTimeout] (../node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (../timers.js:365:14)
      at tryOnTimeout (../timers.js:237:5)
      at Timer.listOnTimeout (../timers.js:207:5)


 RUNS  ...breakpoints.js

[K
[1A
[K
[1A
 RUNS  ...sources.js
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/shlomif/Download/unpack/firefox/debugger.html/assets/build/source-map-worker.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at process.<anonymous> (/home/shlomif/Download/unpack/firefox/debugger.html/node_modules/workerjs/requireworker.js:45:16)
    at process.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/shlomif/Download/unpack/firefox/debugger.html/assets/build/pretty-print-worker.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at process.<anonymous> (/home/shlomif/Download/unpack/firefox/debugger.html/node_modules/workerjs/requireworker.js:45:16)
    at process.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

[K
[1A
[K
[1A
 RUNS  ...sources.js

[K
[1A
[K
[1A
 RUNS  ...sources.js

[K
[1A
[K
[1A
 RUNS  ...sources.js

[K
[1A
[K
[1A
 RUNS  ...sources.js

[K
[1A
[K
[1A
 RUNS  ...sources.js

[K
[1A
[K
[1A FAIL  actions/tests/sources.js (5.766s)

 RUNS  ...sources.js

[K
[1A
[K
[1A  ● Console

    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker
    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker
    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker
    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker
    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker
    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker
    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker
    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker
    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker
    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker
    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker
    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker
    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker
    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker
    console.error ../node_modules/devtools-source-map/src/index.js:42
      Error in source map worker


 RUNS  ...sources.js

[K
[1A
[K
[1A  ● sources › should download a sourcemap and create sources

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at Timeout.callback [as _onTimeout] (../node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (../timers.js:365:14)
      at tryOnTimeout (../timers.js:237:5)
      at Timer.listOnTimeout (../timers.js:207:5)


 RUNS  ...sources.js

[K
[1A
[K
[1A
 RUNS  ...parser.js

[K
[1A
[K
[1A
 RUNS  ...parser.js

[K
[1A
[K
[1A PASS  utils/tests/parser.js

 RUNS  ...parser.js

[K
[1A
[K
[1A
 RUNS  ...ui.js

[K
[1A
[K
[1A
 RUNS  ...ui.js

[K
[1A
[K
[1A PASS  actions/tests/ui.js

 RUNS  ...ui.js

[K
[1A
[K
[1A
 RUNS  ...build-query.js
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/shlomif/Download/unpack/firefox/debugger.html/assets/build/source-map-worker.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at process.<anonymous> (/home/shlomif/Download/unpack/firefox/debugger.html/node_modules/workerjs/requireworker.js:45:16)
    at process.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/shlomif/Download/unpack/firefox/debugger.html/assets/build/pretty-print-worker.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at process.<anonymous> (/home/shlomif/Download/unpack/firefox/debugger.html/node_modules/workerjs/requireworker.js:45:16)
    at process.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

[K
[1A
[K
[1A
 RUNS  ...build-query.js

[K
[1A
[K
[1A PASS  utils/tests/build-query.js

 RUNS  ...build-query.js

[K
[1A
[K
[1A
 RUNS  ...object-inspector.js
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/shlomif/Download/unpack/firefox/debugger.html/assets/build/source-map-worker.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at process.<anonymous> (/home/shlomif/Download/unpack/firefox/debugger.html/node_modules/workerjs/requireworker.js:45:16)
    at process.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

[K
[1A
[K
[1A
 RUNS  ...object-inspector.js

[K
[1A
[K
[1A PASS  utils/tests/object-inspector.js

 RUNS  ...object-inspector.js

[K
[1A
[K
[1A
 RUNS  ...sources.js

[K
[1A
[K
[1A
 RUNS  ...sources.js

[K
[1A
[K
[1A PASS  reducers/tests/sources.js

 RUNS  ...sources.js

[K
[1A
[K
[1A
 RUNS  ...source-search.js

[K
[1A
[K
[1A
 RUNS  ...source-search.js

[K
[1A
[K
[1A PASS  utils/tests/source-search.js

 RUNS  ...source-search.js

[K
[1A
[K
[1A
 RUNS  ...sources-tree.js
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/shlomif/Download/unpack/firefox/debugger.html/assets/build/source-map-worker.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at process.<anonymous> (/home/shlomif/Download/unpack/firefox/debugger.html/node_modules/workerjs/requireworker.js:45:16)
    at process.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

[K
[1A
[K
[1A
 RUNS  ...sources-tree.js

[K
[1A
[K
[1A PASS  utils/tests/sources-tree.js

 RUNS  ...sources-tree.js

[K
[1A
[K
[1A
 RUNS  ...scopes.js

[K
[1A
[K
[1A
 RUNS  ...scopes.js

[K
[1A
[K
[1A PASS  utils/tests/scopes.js

 RUNS  ...scopes.js

[K
[1A
[K
[1A
 RUNS  ...source.js

[K
[1A
[K
[1A
 RUNS  ...source.js

[K
[1A
[K
[1A PASS  utils/tests/source.js

 RUNS  ...source.js

[K
[1A
[K
[1A
 RUNS  ...fromJS.js

[K
[1A
[K
[1A
 RUNS  ...fromJS.js

[K
[1A
[K
[1A PASS  utils/tests/fromJS.js

 RUNS  ...fromJS.js

[K
[1A
[K
[1A
Test Suites: 2 failed, 10 passed, 12 total
Tests:       2 failed, 106 passed, 108 total
Snapshots:   0 total
Time:        21.614s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v0.16.1
$ yarn run lint-css -s && yarn run lint-js -s && yarn run lint-md 
yarn run v0.16.1
$ stylelint "src/components/**/*.css" 
Done in 4.09s.
yarn run v0.16.1
$ eslint "src/**/*.js" 
Done in 27.71s.
yarn run v0.16.1
$ remark -q *.md src/**/*.md configs/*.md docs/**/*.md 
Done in 2.20s.
Done in 35.82s.
yarn run v0.16.1
$ flow 
No errors!
Done in 0.50s.
Done in 60.92s.

```

**Comment by jasonLaster** [comment] 2017-03-24 01:11
This is a duplicate of #2427

**Closed** 2017-03-24 01:11 UTC
