### ISSUE TITLE
[Panes] Deleting your search query when searching for text in the Debugger pane, will reset the text cursor to the beginning of your search query

### ISSUE THREAD

**Issue by tommai78101** [devtools-html/debugger.html#5494] opened 2018-02-21 20:04 UTC
**OS:** Windows 7
**Version:** Firefox Dev Edition 59.0b11 (64-bit)

Steps to reproduce:

1. Find any JS source code you can look at. The code needs to be uglified / minified.
2. Click on the "Format Source Code" in the lower left corner.
3. CTRL+F or CMD+F, whichever works for you.
4. Type anything.
5. Press END.
6. Press Delete.
7. Observe text cursor moving back to the beginning.
8. Repeat Steps 5 ~ 7.

GIF:

![gif](https://user-images.githubusercontent.com/6444116/36502577-635853dc-1718-11e8-9faa-a925dfa1b831.gif)

**Comment by lukaszsobek** [comment] 2018-02-22 17:41
Not able to reproduce it on master.
![peek 2018-02-22 18-40](https://user-images.githubusercontent.com/23530054/36554588-faed8086-17ff-11e8-8329-ff7fa5605be8.gif)

**Comment by tommai78101** [comment] 2018-02-23 14:22
![](https://i.imgur.com/dyN3PYS.png)

Was told the fix isn't in the Firefox Dev Edition branch for Windows 7.

**Comment by jasonLaster** [comment] 2018-02-27 15:09
Thanks @tommai78101 i believe Nightly should be fixed. Let me know

**Closed by jasonLaster** 2018-02-27 15:09 UTC
Labels: not-available
