### ISSUE TITLE
Unresponsive script message when opening sources

### ISSUE THREAD

**Issue by kenjiO** [devtools-html/debugger.html#7434] opened 2018-12-06 19:03 UTC
STR  (on Mac OS)

1. delete `firefox/obj-x86_64-apple-darwin16.7.0/tmp/profile-default` to create a new profile on startup
2. mach run
3. select "Firefox Privacy Notice Tab"
4. Open Debugger
5. Expand Sources
6. Click on various sources

After clicking on a few sources I start to get the beach ball cursor and then get the **Warning: Unresponsive Script** popup

<img width="445" alt="screen shot 2018-12-06 at 10 52 24 am" src="https://user-images.githubusercontent.com/5035181/49605374-285c5700-f945-11e8-8738-24603b20da8e.png">

![](http://g.recordit.co/fweOXqmrOl.gif)

**Comment by nchevobbe** [comment] 2018-12-06 19:06
I had a few of those in the last days too

**Comment by jasonLaster** [comment] 2018-12-11 18:02
yep. closing this as it is a dupe of #7485

**Closed by jasonLaster** 2018-12-11 18:02 UTC
Labels: performance
