### ISSUE TITLE
[EditorSearch] doSearch is slow

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2154] opened 2017-02-26 19:11 UTC
There are some performance issues with search at the moment

1. getSearchState is called all the time
1. getSearchState creates the search matches inneficiently

**Comment by wldcordeiro** [comment] 2017-02-28 07:51
@jasonLaster seemed to address this so I'm closing for now. If we find that there's still slowness we can reopen or whatever.

**Comment by jasonLaster** [comment] 2017-03-02 19:28
We fixed the initial concern about search slowing down viewing a source, but we should fix the secondary concern of search being slow in general. This effects opening and closing the search bar as well as updating searches.

**Comment by jasonLaster** [comment] 2017-03-05 00:08
The easiest way to test this is to debug a big file and turn on the profiling tools and then hit `<cmd>+f`


```diff
diff --git a/src/utils/editor/source-search.js b/src/utils/editor/source-search.js
index a40f31a..f8b0bae 100644
--- a/src/utils/editor/source-search.js
+++ b/src/utils/editor/source-search.js
@@ -35,6 +35,9 @@ function getSearchState(cm: any, query, modifiers) {

   state.results = [];
   while (cursor.findNext()) {
+    // this is the place i think we're slow...
+    // i bet we can do this in batch or a regex...
+    // also we can lean on CM and do a PR up stream
     state.results.push(cursor.pos);
   }
```

**Comment by wldcordeiro** [comment] 2017-03-05 00:24
@jasonLaster I thought that while loop looked like it could be problematic. Must be a way to reduce the overhead.

**Comment by ryanjduffy** [comment] 2017-03-09 22:22
Starting looking at this. At least a portion of the issue is that CodeMirror mutates a lot of DOM nodes when a search is performed. In the profiler, a bulk of the time in FF was spent in styling. Chrome didn't exhibit the same lag on showing the search bar but actually searching was slow in both.

**Comment by ryanjduffy** [comment] 2017-03-09 22:54
Adding a guard in `toggleSearch()` seems to improve the common case of just starting a search by cmd+f. Doesn't get to the root cause, of course.

```
      if (selection) {
        this.setSearchValue(selection);
        this.doSearch(selection);
      }
```

**Comment by ryanjduffy** [comment] 2017-03-09 23:56
May need some upstream changes to fix this. CM has a `viewportMargin` property to manage the amount of code rendered at any point in time. Unfortunately, it limits it line and not by width. So, if you have a large, many lined, file, the performance isn't too bad. If you have a large, few lines but very wide (e.g. minified file), you're still out of luck.

**Comment by jasonLaster** [comment] 2017-03-10 00:07
@ryanjduffy thanks for the research. A good test to try this on is the debugger's `bundle.js`, which you can get to by having the debugger opened in firefox. This case does not have many long lines, but is still slow.

**Comment by ryanjduffy** [comment] 2017-03-10 20:56
Created a rough PR to start some discussion. Seems to improve search bar and search performance on large files but could use some more informed eyes on it!

**Closed** 2017-03-13 13:58 UTC
Labels: bug, difficulty: medium, Mentor, performance, up for grabs
