### ISSUE TITLE
Files list (left panel) can't be scrolled with a long list of files.

### ISSUE THREAD

**Issue by karlcow** [devtools-html/debugger.html#864] opened 2016-10-04 02:46 UTC
STR:
1. With a clean profile of Firefox Nightly 52.0a1 (2016-10-03) (64-bit)
2. Enter a URL with a lot of JS, for example https://www.nitori-net.jp/store/ja/ec/7514915
3. Open debugger panel
4. Put your cursor above the left side aka [Sources] (with two fingers try to scroll up and down). 

Expected: List of files is scrolling
Actual: files list is fixed, files out of sight can't be reached (except if closing some of the domains with the arrow widgets)

**Comment by wldcordeiro** [comment] 2016-10-04 02:58
@karlcow thanks for this issue, I've found the cause of this and will be putting a PR in with a fix. Nightly will likely remain broken however for a week or so to wait for some other changes.

**Comment by jasonLaster** [comment] 2016-10-06 16:05
Fixed in #865

**Closed by jasonLaster** 2016-10-06 16:05 UTC
Labels: bug
