### ISSUE TITLE
 Clicking on links in debugger for eval code open a 404

### ISSUE THREAD

**Issue by miketaylr** [devtools-html/debugger.html#2185] opened 2017-02-27 20:41 UTC
If you end up inside a stacktrace that had some eval code, the debugger links don't do anything useful.

STR:

1) open https://miketaylr.com/bzla/eval-script.html
2) open debugger
3) expand `TypeError` stacktrace
4) click on `<anonymous> https://miketaylr.com/bzla/eval-script.html%20line%205%20%3E%20eval:2:1`

Expected: I see the source code
Actual: I end up at "view-source:https://miketaylr.com/bzla/eval-script.html%20line%205%20%3E%20eval", which is a 404.

This reproduces on other sites, in case someone suspects I have a crappy server setup.

**Comment by StephaneHe** [comment] 2017-03-15 19:48
Couldn't it be a Firefox bug, as I can reproduce this without debugger-html actually running ?

view-source:https://miketaylr.com/bzla/eval-script.html will bring your actual html source page. 

Add anything to it (line number or anything else) and it will just bug. Likewise for any other web page actually.

**Comment by jasonLaster** [comment] 2017-08-01 17:41
@nchevobbe is this a console bug or debugger bug?

**Comment by nchevobbe** [comment] 2017-08-02 11:59
I'm seeing this error with the old console + old debugger as well, so it might be more something related to the server I guess.

In the new console, we use the [Stacktrace component](http://searchfox.org/mozilla-central/source/devtools/client/shared/components/stack-trace.js#31) which we pass [the stacktrace we get from the packet](http://searchfox.org/mozilla-central/source/devtools/client/webconsole/new-console-output/test/fixtures/stubs/pageError.js#182) and [this function to load the file in the debugger](http://searchfox.org/mozilla-central/source/devtools/client/webconsole/new-console-output/new-console-output-wrapper.js#101), which I think in the end calls [this function](http://searchfox.org/mozilla-central/source/devtools/client/shared/view-source.js#53).

What must happen here is that the source is probably not in the debugger, and then http://searchfox.org/mozilla-central/source/devtools/client/shared/view-source.js#62-63 falls back to `viewSource`.
Not sure if I got this all right and if the debugger should have `https://miketaylr.com/bzla/eval-script.html%20line%205%20%3E%20eval:2:1` as a source (i'd say no, since it has already the html file). or if this source is not built as it should on the server side.

**Comment by jasonLaster** [comment] 2017-10-17 22:50
Just looked into it again and I think it's an issue with how the source url is represented in the server:

take a look at this [example](https://bad-eval.glitch.me/)

```js
function stuff() {
  console.log("why, hello there!")
  var script = "if(true) {\nundefined()\n}";
  eval(script);
}
```

The log URL is fine, but the eval is not. Notice `%20`... 

<img src='https://shipusercontent.com/7bb0e1822c91dd07e6f275669d58a364/Screen%20Shot%202017-10-17%20at%206.49.59%20PM.png' title='Screen Shot 2017-10-17 at 6.49.59 PM.png' width=426>

**Comment by jasonLaster** [comment] 2017-10-17 22:53
moving to bugzilla so it can be tracked by the console component:

https://bugzilla.mozilla.org/show_bug.cgi?id=1409571

**Closed by jasonLaster** 2017-10-17 22:53 UTC
Labels: bug, panel

**Comment by miketaylr** [comment] 2017-10-26 21:35
Thanks!
